### ISSUE TITLE
Add support for form in jetengine

### ISSUE THREAD

**Issue by ttctst** [hCaptcha/hcaptcha-wordpress-plugin#104]
I wnat to use hcaptcha  in jetengine ., but it seems not support jeteninge now . Plz help me to solve the problem

**Comment by kagg-design** [comment]
JetEngine is a paid plugin for Elementor and Gutenberg, as far as I know. I don't have it. Please provide a copy for testing via https://kagg.eu/en/contacts/.

**Comment by mbhzpi** [comment]
I also need the support for Jetengine Forms. 
What do you mean with "provide a copy for testing", we should send you the package?
