### ISSUE TITLE
Add support for elementor

### ISSUE THREAD

**Issue by KreatifDesign** [hCaptcha/hcaptcha-wordpress-plugin#105]
Any idea if support for elementor forms will be added?

**Comment by Tanman897** [comment]
Yeah, this is long overdue. Please add Elementor Forms support.

**Comment by kagg-design** [comment]
@Tanman897 do you see my question above? I cannot proceed without an answer.

**Comment by Tanman897** [comment]
@kagg-design I have not ever used the free version of Elementor. In Elementor Pro, form is a widget option in the Elementor page builder interface. But your question is not related to this issue nor even to hcaptcha at all. You really should be asking this elsewhere or Googling it yourself.

**Comment by kagg-design** [comment]
Elementor Pro forms support added in v1.13.0. We will publish it at the end of September.
