### ISSUE TITLE
Add more support for Woocommerce...

### ISSUE THREAD

**Issue by erikdemarco** [hCaptcha/hcaptcha-wordpress-plugin#107]
Woocommerce have builtin order tracking located at https://yoursite.com/track-order/
or if you can't find it use 'woocommerce_order_tracking' shortcode

Please add capabilities to add capthca to these tracking order page.

**Comment by kagg-design** [comment]
Are you sure? Attempt to use such an URL with just WooCommerce installed gives 404. Same with /my-account/track-order. Same with Storefront theme.

Please clarify.

**Comment by kagg-design** [comment]
Support for WooCommerce Order Tracking form added in v1.13.0, which will be published soon.
