### ISSUE TITLE
Login/register/password forms layout issue

### ISSUE THREAD

**Issue by Player701** [hCaptcha/hcaptcha-wordpress-plugin#113]
Hello there.

This is purely a visual issue. The captcha itself seems to work fine for me, but either the login form needs to be a little wider, or the captcha element itself should be a bit shorter.

![image](https://user-images.githubusercontent.com/9046118/133910305-d96cd944-b008-4f92-99ed-52e184d88057.png)

It looks the same on the registration and password recovery forms, too.

**Comment by kagg-design** [comment]
Fixed in v.1.13.0, which will be published soon.

**Comment by Player701** [comment]
Thanks!
