### ISSUE TITLE
Broken WooCommerce order tracking page

### ISSUE THREAD

**Issue by pjv** [hCaptcha/hcaptcha-wordpress-plugin#119]
@kagg-design v. 1.13.1 breaks order tracking on a site I manage. I have created a test order on the site and I am emailing you the link and order number to the email in your github profile. Can you tell from the page source why the hCaptcha is not rendering and why the page errors with "please complete the captcha"?

Currently I have the tracking page option checked:
![2021-10-22 at 2 29 PM](https://user-images.githubusercontent.com/327716/138512461-4b33b57d-6cd9-4a63-9a11-1f3e8f0fd3f0.jpg)

...but the page behaves identically with that option unchecked. As of now the hcaptcha plugin is completely incompatible with the tracking page on this site. I downgraded to v. 1.13.0 and also to 1.12.0 and saw the same issue.

**Comment by kagg-design** [comment]
I have tried to fix it without testing on your site, but it should work in 1.13.2. We will release it in a few days. Please let me know.

**Comment by kagg-design** [comment]
1.13.2 is released.

**Comment by pjv** [comment]
>I have tried to fix it without testing on your site, but it should work in 1.13.2. We will release it in a few days. Please let me know.

1.13.2 does not fix the issue on our site. 

If you take a look at the source of the tracking page here: https://breadtopia.com/track-order/ you will see that our theme is rendering several hidden forms on the page which allow the user to login or register in a “popup”. It seems that the hcaptcha plugin is getting confused about which form is visible and is rendering the captcha inside one of the invisible forms. The user cannot see or interact with the captcha and thus every submit is a failed captcha and does not pass validation.

In the hcaptcha plugin settings, I tried toggling off every type of compatibility in use on the site (woocommerce registration form, CF7, woocommerce order tracking) and even in that case when I could find no hcaptcha even being rendered in hidden forms on the page, submitting the order tracking form with valid data resulted in an invalid captcha error message.

**Comment by kagg-design** [comment]
Please provide me with the sequence of the steps how to reproduce your issue on the fresh WP site: which theme, plugins I have to install (a minimal set). If you have premium plugins or the theme involved, I need .zip files, please send them by email.

**Comment by e271828-** [comment]
@pjv aside: big fan of breadtopia :)

**Comment by pjv** [comment]
@kagg-design 
>  If you have premium plugins or the theme involved, I need .zip files, please send them by email.

I did email you a zip with our custom theme on 10/23. I will set up a fresh, vanilla testing platform and confirm whether another plugin is involved. Likely I will find the issue myself in that context and submit a PR. If I cannot, then I will detail the steps to set up the same minimal config.

**Comment by pjv** [comment]
@kagg-design 

Two things:

1. (relatively unimportant) I was able to get the hcaptcha to render on the tracking page on my site by making a small adjustment to a regex in `src/php/WC/OrderTracking.php`.

does not work: ...`|<p class="form-actions">[\S\s]+?<button type="submit")/i`

works: `...|<p class="form-actions"><button type="submit")/i`

2. (more important) With a plain vanilla wordpress v. 5.8.2, woocommerce 5.9.0, hcaptcha 1.13.2, and using theme twenty twenty-one, if the hcaptcha plugin is active, submitting the tracking page form always gives a “please complete the captcha” error, regardless of whether the plugin is set to apply to the woocommerce tracking page or not and regardless of whether the captcha, if rendered, is correctly completed. 

![2021-11-15 at 9 26 AM](https://user-images.githubusercontent.com/327716/141808481-af1b337c-3e53-4808-9146-ed03a0074232.jpg)

Activating the hcpatcha plugin at all seems to break the woocommerce tracking form as far as I can tell. If it’s not something weird in my test environment, you should be able to reproduce this by installing woocommerce 5.9.0 and hcaptcha 1.13.2 on a fresh WP install with twenty twenty-one, creating a new “tracking” page and putting the shortcode: `[woocommerce_order_tracking]` as the sole content on that page. Then create an order in woocommerce and visit the tracking page and fill in the form with your WC order number and email and submit the form.

**Comment by pjv** [comment]
Digging through the source code and tracing execution on my test environment, it looks like function `hcaptcha_request_verify` in `/src/php/includes/common/request.php` is returning `empty` because there is no HCAPTCHA_NONCE (const is set to 'hcaptcha_nonce') nonce being set in the form on the order tracking page. The only nonce I see in the form on that page is called `woocommerce-order-tracking-nonce`.

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/6d74a2e838992d789ef4d7c516502c3543963398/src/php/includes/common/request.php#L60-L67

The result of that function returning `empty` (instead of `success`) is the following which is consistent with the behavior I am seeing:

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/6d74a2e838992d789ef4d7c516502c3543963398/src/php/AutoVerify/AutoVerify.php#L100-L110

**Comment by pjv** [comment]
I submitted a fix for this issue in PR #129.

**Comment by kagg-design** [comment]
> 1. (relatively unimportant) I was able to get the hcaptcha to render on the tracking page on my site by making a small adjustment to a regex in `src/php/WC/OrderTracking.php`.
> 
> does not work: ...`|<p class="form-actions">[\S\s]+?<button type="submit")/i`
> 
> works: ...`|<p class="form-actions"><button type="submit")/i`
> 

As I wrote in the PR, I have fixed this by `[\S\s]+?`. Thank you,

**Comment by kagg-design** [comment]
> 2. (more important) With a plain vanilla wordpress v. 5.8.2, woocommerce 5.9.0, hcaptcha 1.13.2, and using theme twenty twenty-one, if the hcaptcha plugin is active, submitting the tracking page form always gives a “please complete the captcha” error, regardless of whether the plugin is set to apply to the woocommerce tracking page or not and regardless of whether the captcha, if rendered, is correctly completed.


I cannot reproduce it. Can you give me access to your test environment?

**Comment by kagg-design** [comment]
> 2. (more important) With a plain vanilla wordpress v. 5.8.2, woocommerce 5.9.0, hcaptcha 1.13.2, and using theme twenty twenty-one, if the hcaptcha plugin is active, submitting the tracking page form always gives a “please complete the captcha” error, regardless of whether the plugin is set to apply to the woocommerce tracking page or not and regardless of whether the captcha, if rendered, is correctly completed.

Thank you, you are right. I have added the hCaptcha nonce.
