### ISSUE TITLE
Usage with WP API

### ISSUE THREAD

**Issue by n-kort** [hCaptcha/hcaptcha-wordpress-plugin#122]
I'm using [hCaptcha/vue-hcaptcha](https://github.com/hCaptcha/vue-hcaptcha) and posting form data (including `h-captcha-response`) to `/wp-json/wp/v2/comments`. Always responds with 400 'Invalid Captcha' though. Any pointers as to how (or whether) this should work?

I've tried generating and including a `hcaptcha_nonce` or `hcaptcha_comment_form_nonce` but to no avail...

The captcha works fine on the WP login page.

**Comment by e271828-** [comment]
Hmm, seems likely to be nonce-related. Did you take a look at your backend logs?

**Comment by n-kort** [comment]
I didn't look at this again but yes, that is most likely the case :) I was returning the nonce from a custom endpoint but the user is always `0` in that context, so it will not (and probably shouldn't) work in that case.
