### ISSUE TITLE
Add Support for Avada WordPress Theme / Website Builder

### ISSUE THREAD

**Issue by mn-martin** [hCaptcha/hcaptcha-wordpress-plugin#123]
Hello,

please consider adding support for [Avada WordPress Theme / Website Builder (740,752 sales)](https://themeforest.net/item/avada-responsive-multipurpose-theme/2833226).

**Comment by hcuk94** [comment]
Would also be keen to see this, Avada has a forms module which would benefit from easy integration with hCaptcha.

**Comment by Eisfluegel** [comment]
+1 from me as well

**Comment by kagg-design** [comment]
@mn-martin @hcuk94 @Eisfluegel Could you share the Avada theme with me and send it to info@kagg.eu?

**Comment by Eisfluegel** [comment]
@kagg-design I sent you an email with the Avada files. Please check if you got it (maybe it will be in the spam folder).

**Comment by kagg-design** [comment]
@Eisfluegel Thank you, well received. I will work on it soon.

**Comment by kagg-design** [comment]
@mn-martin @hcuk94 @Eisfluegel I have added Avada support in v2.2.0. It will be published soon. So far, you can use it from this commit 1a27c1ac3f6954f09818a18724568b117ba1d449 in v2.2.0 branch.
