### ISSUE TITLE
Hcaptcha not working

### ISSUE THREAD

**Issue by khizer253** [hCaptcha/hcaptcha-wordpress-plugin#124]
Hcaptcha not working in contact form 7 wordpress its show error invalid captcha
![image](https://user-images.githubusercontent.com/80098275/139383805-7b7e891d-414e-40a0-a728-50823d94a326.png)

**Comment by kagg-design** [comment]
Please find out what kind of conflict do you have. Deactivate all plugins except CF7 and Captcha, change your theme to standard.

Without it, I don't know how to help.
