### ISSUE TITLE
Fatal Error with Elementor 3.5.0 update

### ISSUE THREAD

**Issue by pBrambi** [hCaptcha/hcaptcha-wordpress-plugin#125]
Hello,

pretty urgent I think. Elementor 3.5.0 was release a 2 days ago, and 4 sites, which I have hCaptcha plugin activated for "Elementor Pro Forms" are getting "Fatal Error". 

No output, just the Wordpres "A fatal error occured on this website" message.

When I delete the plugin from FTP, site works. When re-activating, again fatal error.

Tried on new site with just Elementor Pro and hCaptcha plugin, same issue.

Thanks.

**Comment by kagg-design** [comment]
Fixed in V1.13.2, will be published in a few days.

**Comment by kagg-design** [comment]
1.13.2 is just published, please use it.
