### ISSUE TITLE
hcaptcha/ contact form 7 on wordpress not working 

### ISSUE THREAD

**Issue by CatieGit** [hCaptcha/hcaptcha-wordpress-plugin#126]
hello, on the settings of hcaptcha Plugin in wordpress Setup I checked the integration for contact form7. I havent found any other setting to integrate hcaptcha to contact form 7... my hcaptcha is working on login page, but not on my forms... can you help?

https://alpha4u-bildung.de/kontakt/

**Comment by kagg-design** [comment]
This is because your theme (Qode?) modifies the CF7 form. Edit the CF7 form manually in the admin and insert into it the following shortcode:

`[cf7-hcaptcha]`
