### ISSUE TITLE
hCaptcha not working anymore since update

### ISSUE THREAD

**Issue by Jumper34** [hCaptcha/hcaptcha-wordpress-plugin#127]
Hi,

since about mid-October the hcaptcha wordpress plugin seems to have a conflict with my other plugin: https://marketplace.appthemes.com/plugins/confirm-email/

All worked fine until then. Now the invisible hcaptcha is asking to pick the pictures and then after it was passed, the confirmation email is not send to users anymore. Thus they can not register to my site.
It might be the WP update or hCaptcha or the mentioned plugin. Any idea? If I use the setting "normal" or "compact" in hcaptcha the confirmation email is send. (For now, I switched back to reCaptcha).

I am writing to AppTheme too.
Link to our webpage below.
Thank you

Chris

Be The Hero Of The Animals On Your Street!
https://kirikkuyruk.com

**Comment by kagg-design** [comment]
Hi Chris,

I cannot check the case as I do not have this premium plugin. You can send its zip file to my email. 

Additionally, please describe the scenario - which steps should I follow from an empty WP site to see the problem?

Thank you.
