### ISSUE TITLE
hCaptcha causing "Invalid Login Credentials" 

### ISSUE THREAD

**Issue by canyon1991** [hCaptcha/hcaptcha-wordpress-plugin#130]
hCaptcha is causing "Invalid Login Credentials" on the WordPress login page.

When the plugin is active, I cannot login using my login details. Once disabled, the same login details work fine. 

Website Info:
WordPress (Version 5.8)
PHP (Version 7.4.25)
WooCommerce (Version 5.7.0)
All in One WP Security (Version 4.4.9)
WPBakery Page Builder	(Version 6.7.0)
hCaptcha for Forms and More (Version 1.13.2)

Let me know if more information is necessary.

**Comment by kagg-design** [comment]
I cannot reproduce the issue, with the same plugins. Could you try to find out the minimal set of plugins + standard theme and describe steps I have to do to reproduce?

Thank you.
