### ISSUE TITLE
Safari issue with hcaptcha.js, unexpected token

### ISSUE THREAD

**Issue by JosephMDavis** [hCaptcha/hcaptcha-wordpress-plugin#131]
Running WP 5.8.2 and "hCaptcha for Forms and More" 1.13.2.

Getting "SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list" when Safari loads hcaptcha.js, line 40.

Seems that Safari < 14.1 doesn't support "public field declarations".

This prevents hcaptcha from loading and the user is given errors that they need to complete the captcha, which they don't see.

![59_GMT-0600_Central_Standard_Time](https://user-images.githubusercontent.com/1726617/144890280-b384033f-820c-4a04-83eb-2abd4ce761d3.png)

**Comment by e271828-** [comment]
@kagg-design I think this JS should be babel'd to ES5 at build, rather than included directly in the assets dir. Looks like it's using arrow functions etc.

**Comment by kagg-design** [comment]
@e271828- Yes, the reason is the usage of arrow functions. Webpack + babel added.

@JosephMDavis Fixed in v1.13.4; it will be released soon.
