### ISSUE TITLE
Plugin is not getting activate 

### ISSUE THREAD

**Issue by Shail92** [hCaptcha/hcaptcha-wordpress-plugin#132]
Hello Team, 

On activating the plugin it shows the error as shown in the below screen.

![image](https://user-images.githubusercontent.com/96033642/145744935-1c3e2528-4489-43c7-9633-20f3808cf7d4.png)

**Comment by e271828-** [comment]
Got any more details? Does this happen on a clean install?

**Comment by Shail92** [comment]
Hello Team,

Yes, It's happing with a clean installation, We have never used it before, I did the clean installation on activating we are getting errors.

Note: Tired on multiple sites in all had same issues.

**Comment by e271828-** [comment]
@Shail92 which WP version is this?

**Comment by Shail92** [comment]
@e271828- I can confirm that the site which I tried is all above 4.8 versions. The issue comes when I try to activate the plugin.

**Comment by e271828-** [comment]
@Shail92 just to confirm, by "clean install" you mean there are no other plugins installed? If so, cannot reproduce. Please attach the server logs and exact WP version.

**Comment by Shail92** [comment]
@e271828- no I tried to install it on the live site with another plugin that is enabled.

**Comment by e271828-** [comment]
> @e271828- no I tried to install it on the live site with another plugin that is enabled.

OK, which plugin was that?

**Comment by Shail92** [comment]
I have tried 4-5 sites in all I had different plugins so, I can't remember all the plugins.

**Comment by kagg-design** [comment]
You tried to use the plugin version from GitHub (see the directory name on your screenshot). Upon downloading from GitHub, you have to run `composer install`, as README.md says.

I'd rather recommend downloading the plugin from wp.org: https://wordpress.org/plugins/hcaptcha-for-forms-and-more/
