### ISSUE TITLE
Possibility to show hcaptcha only after certain times of failed login?

### ISSUE THREAD

**Issue by heiheiheihei9** [hCaptcha/hcaptcha-wordpress-plugin#133]
Hello, It is possible to show the hcaptcha only after certain times of failed login in order to prevent the bots, but at the same time not to make the login inconvenient?

**Comment by kagg-design** [comment]
Please do not create PR just to attract attention. I have seen your current issue here and on wp.org. However, I have no time right now to implement it.

PR from you with the proposed code of this feature is welcome.

**Comment by kagg-design** [comment]
I have added this feature to v2.4.0, which will be released soon.
