### ISSUE TITLE
Hcaptcha only for admin login not for woocommerce login

### ISSUE THREAD

**Issue by heiheiheihei9** [hCaptcha/hcaptcha-wordpress-plugin#134]
Hello, it is possible to apply hcaptcha only in the wordpress admin login, but not to woocommerce login form? Because in the current version, if I activate "LOGIN", also on the woocommerce login form the hcaptcha is loaded

**Comment by kagg-design** [comment]
Thank you for reporting. I have fixed this bug in v1.13.4. It will be published soon.
