### ISSUE TITLE
Integration for wp-signup.php / multisite support

### ISSUE THREAD

**Issue by thomasdiesenreiter** [hCaptcha/hcaptcha-wordpress-plugin#142]
We run a multisite installation with about 10 websites. We activated the plugin network wide, but sadly we have to configure it on every website individually. it would be great if a network wide activation would allow you to configure it network wide as well.
Furthermore our main problem is bots trying to sign up via the wp-signup.php page, for which the plugin currently doesn't work as well. It would be great if this could be supported too!
Thanks

**Comment by miguelurtado** [comment]
Great integration.

**Comment by kagg-design** [comment]
Support for wp-signup.php was added in v1.13.0, in September 2021. Support of multi-site added now, in v2.0.0, which will be released at the end of this month.

![image](https://user-images.githubusercontent.com/28291450/192158761-f495270c-91cf-48e7-9000-b67117843ffc.png)
