### ISSUE TITLE
Login - Register Not working with Essential Addons for Elementor

### ISSUE THREAD

**Issue by Jizzbits** [hCaptcha/hcaptcha-wordpress-plugin#144]
I'm using Essential Addons for Elementor for my customer login. Hcaptcha does not show on any forms other than the main Wordpress Admin Login. What's more interesting is when I try to login, it fails. I'm thinking this is due to not having solved the hCaptcha which isn't showing up. I have selected what I believe are the appropriate settings in hCaptcha and can provide screenshots upon request. At this point I think it's due to a lack of integration from Essential Addons, as they have directed me back to reCaptcha.

I am looking for help to solve and I'm open to suggestions.

**Comment by kagg-design** [comment]
We do not support Essential Addons so far. To understand the issue, I need info on all versions: WP, Elementor, Essential, hCaptcha, theme. It would be good to see the video with what you are doing. We can include the issue in our plan, but I cannot say when.

I will need a copy of the Essential plugin later to debug the issue.

Thank you.

**Comment by kagg-design** [comment]
Closed as non-reproducible.
