### ISSUE TITLE
hCaptcha not working - Contact form 7

### ISSUE THREAD

**Issue by PrachiBR** [hCaptcha/hcaptcha-wordpress-plugin#146]
I have integrated hCaptcha on one of our site, Its working everywhere else but not for the contact form 7.

**Comment by kagg-design** [comment]
Please provide more details: versions of WP, PHP, plugins, theme and video showing the issue.

Otherwise, it is impossible to help.

Thank you.

**Comment by pilotofsky** [comment]
I get this error when added hCaptcha in Contact form 7. I have no idea why it is doing that can you please help?

![image](https://user-images.githubusercontent.com/68122496/159030426-3d8caeb2-eeac-4faf-9882-436d8e1bc3a9.png)

**Comment by kagg-design** [comment]
Closed as non-reproducible.
