### ISSUE TITLE
When submit hcaptcha not showing any error

### ISSUE THREAD

**Issue by patrixstar** [hCaptcha/hcaptcha-wordpress-plugin#148]
Hello guys,

i wonder where may i be stuck. When i submit my form (via cf7 in wp) without hcaptcha solved, i am expecting any error/warning response like shown in hcaptcha demo but i am not getting any. Like "you didn't solve captcha correctly" or sth like that. Any suggestions? Do i have to do some coding or setting any css? 

Expected behavior:
![image](https://user-images.githubusercontent.com/34099925/154096182-a94e7327-f593-49cb-acb3-21be27666e23.png)

**Comment by kagg-design** [comment]
I cannot confirm this issue. It could be that REST is disabled on your site or something else creates the problem. To help, I need more information, including console and log file errors.
