### ISSUE TITLE
hCaptcha + Ninja Forms: submissions of multiple forms on single page cause hCaptcha validation failures

### ISSUE THREAD

**Issue by Kimitri** [hCaptcha/hcaptcha-wordpress-plugin#149]
When a page includes multiple NF forms only the first submission is validated correctly. After the first submission all submissions fail CAPTCHA validation. I believe this is caused by the fact that all NF forms on the page contain the same hCaptcha nonce.

**Comment by kagg-design** [comment]
Fixed in v1.15.0, will be released soon on wp.org.
