### ISSUE TITLE
JetEngine Forms Support?

### ISSUE THREAD

**Issue by mbhzpi** [hCaptcha/hcaptcha-wordpress-plugin#150]
Hi,

I use the wordpress plugin "JetEngine", but there is no option to show the hCaptcha on a JetEngine Form. How can I integrate the hCaptcha-Tool into a JetEngine Form? Do you support this plugin?

Kind regards
Matthias

**Comment by kagg-design** [comment]
We do not support JetEngine. This is a premium plugin, and you can ask the producer for support.

Or, you can share the copy of JetEngine with us, but we cannot guarantee when we can make the integration. We have a lot of similar requests.

**Comment by kagg-design** [comment]
Closed as no response.
