### ISSUE TITLE
Remove <br> when WPCF7_AUTOP is set to false

### ISSUE THREAD

**Issue by dhalucario** [hCaptcha/hcaptcha-wordpress-plugin#152]
When creating a contact form in WPCF7 using hcaptcha it adds a `<br>` before the submit button.
This should not happen when WPCF7_AUTOP is set to false.

**Comment by kagg-design** [comment]
Without `<br>`, the form will look like that

![image](https://user-images.githubusercontent.com/28291450/163719120-2a0bfe6c-8b74-49cf-a9b4-35d3addb186b.png)

At any time, you can filter the form and remove `br`

```
function my_wpcf7_form_elements( $form ) {
	return str_replace(
		'<br><input type="submit"',
		'<input type="submit"',
		$form
	);
}

add_filter( 'wpcf7_form_elements', 'my_wpcf7_form_elements', 20 );
```

**Comment by dhalucario** [comment]
Hello @kagg-design,

to my understanding this is kind of the point? wpautop causes newlines to be converted to br's and p's respectively. Usually when disabling wpautop using `WPCF7_AUTOP`  the intent of the user is for these to be not output. It'd make more sense to put a new line after the hcaptcha so wpautop creates it when needed. I am aware that there is a filter but that's not why I created the issue.

See:
https://developer.wordpress.org/reference/functions/wpautop/
https://contactform7.com/controlling-behavior-by-setting-constants/ (Scroll down to `WPCF7_AUTOP`)

**Comment by dhalucario** [comment]
@kagg-design Would you be kind enough to reopen this issue?

**Comment by kagg-design** [comment]
I do not understand the issue - can you show me the broken form? What happens with/without wpautop?
