### ISSUE TITLE
Feature request : IP whitelisting

### ISSUE THREAD

**Issue by sertys3** [hCaptcha/hcaptcha-wordpress-plugin#153]
Thanks to community for the wonderful work so far.
I would like to submit this FR as it is instrumental to many organizations/enterprises. Having whitelisting for certain IPs would be great in terms of usability for deployments that have daily users. It would be great to have a whitelist configuration in the plugin as to bypass captcha for certain IPs.

Regards,
Daniel

**Comment by kagg-design** [comment]
Done in v1.15.0. You can get it from the branch or wait for the release on wp.org, which we will make soon.
