### ISSUE TITLE
Ultimate Member

### ISSUE THREAD

**Issue by rontech2020** [hCaptcha/hcaptcha-wordpress-plugin#155]
Compatibility with Ultimate Member.

I wanted to know if it was possible to add hcapcha in Ultimate Member in any way in order to verify people at login and registration.

**Comment by kagg-design** [comment]
Added in v1.17.0.

**Comment by rontech2020** [comment]
Ciao, riscontriamo problemi con l’accesso e la conferma su tutti i nostri siti.Grazie.Ronzani SamueleIl giorno 27 ago 2022, alle ore 21:32, Igor at KAGG Design ***@***.***> ha scritto:﻿
Added in v1.17.0.
