### ISSUE TITLE
Challenges with popular form integrations

### ISSUE THREAD

**Issue by aaronware** [hCaptcha/hcaptcha-wordpress-plugin#160]
The plugin has the opinion that the hCaptcha field should be added to ALL forms if enabled. But that isn't always the intended use case. I know you are trying to support a lot of different popular form plugins. For Gravity Forms for example. The hCaptcha should be treated like a Gravity Forms field. OR at minimum there should be some sort of filter available for developers to show or hide accordingly vs on the `init`. If you'd like I can fork and do a pull request to at least get a filter going

**Comment by e271828-** [comment]
Sure, PRs always welcome.

**Comment by pk385** [comment]
Coming back to this after looking at it and thinking about it for a while, I can't come up with a more universal solution that will work for more form plugins. I think using either a CSS class or ID on the form or form element(s) as a flag to decide when to inject the captcha is probably the easiest to implement and would work with the majority of forms. Using shortcodes is the more "wordpress" solution but not all form plugins support inserting shortcodes in the form and those that do may require pro versions.

**Comment by kagg-design** [comment]
The implementation was added in v2.8.0 for several plugins and expanded in v2.9.0. The filter  `hcap_protect_form` is described in the readme.txt.
