### ISSUE TITLE
Integration: Gravity Forms : hCaptcha "Field" is not required or tied into submission

### ISSUE THREAD

**Issue by aaronware** [hCaptcha/hcaptcha-wordpress-plugin#161]
This allows the recaptcha by default to be skipped from the front end as well as the backend (If there is any sort of configuration for that similar to reCaptcha)

**Comment by aaronware** [comment]
I am not affiliated with this plugin nor do I vouch for any sort of coding standards within it but this looks like they have done a lot of the leg work for proper integration with gravity forms as was mentioned in #49. May be worth reaching out to that developer to merge these 2 plugins into 1?

**Comment by kagg-design** [comment]
Closed as non-reproducible.
