### ISSUE TITLE
elementor pro (3.7.0) with hCaptcha (1.15.0) 

### ISSUE THREAD

**Issue by danypu** [hCaptcha/hcaptcha-wordpress-plugin#162]
Hi Team,

I will use the hcaptcha plugin with elementor pro but I can’t chose it in the Formfields, it is still not listed.
It docent work before and after the latest update of hcapture and elementor and Wordpress.
I have insered the Site and Secret Key
I activated in the prev panel:
- Turn off when logged in
- Enable hCaptcha on Elementor Pro Form 

What can I do?
Chers, Daniel

Setting:
Elementor v3.6.5
Elementor Pro v3.7.0
WordPress 5.9.3
hCaptcha 1.15.0

**Comment by kagg-design** [comment]
I cannot reproduce it - it is listed

![image](https://user-images.githubusercontent.com/28291450/169699108-c66a7db7-4067-41f1-94f1-fc53353adf51.png)

**Comment by kagg-design** [comment]
@danypu, with the help of @MarkWest2017, I have reproduced and fixed the issue. v1.19.0 should be released today, 30-Aug.
