### ISSUE TITLE
support@hCaptcha sent me here

### ISSUE THREAD

**Issue by TidyBowlMan** [hCaptcha/hcaptcha-wordpress-plugin#163]
Hello there,

I was wondering if there was a simple CSS fix to changing the color of the hCaptcha button? This is my site and I want to make the color of the checkbox a little darker and the entire button itself the same color as the input fields you see there now. Can you point me in the proper direction. Usually i would use developer tools but the css is an element/inline so I can't seem to grab what I need.

https://sunshinewildlifetours.com/?page_id=69

Kind regards,
TidyBowlMan

**Comment by kagg-design** [comment]
Unfortunately, the WordPress plugin cannot change the colour of the button. It is formed in the iframe by the js code from the hcaptcha.com website. All that you can do with the plugin, is to switch the theme from light to dark. You can do it on the plugin settings page.

More precisely selection of the button colour requires changes in the js code on hcaptcha.com. So, you should address your request there.
