### ISSUE TITLE
HI i did all the steps to setup hcaptcha but doesn't' work

### ISSUE THREAD

**Issue by MBNChannel** [hCaptcha/hcaptcha-wordpress-plugin#166]
HI i did all the steps to setup hcaptcha but doesn't' work.
![unnamed](https://user-images.githubusercontent.com/107365459/173247043-92af5c93-fe32-435a-8db5-b0992e8ec7e8.png)
![unnamed (2)](https://user-images.githubusercontent.com/107365459/173247052-309938b5-c912-403c-a58d-9d038f1d5d48.png)
![unnamed (1)](https://user-images.githubusercontent.com/107365459/173247058-c88cf0e2-8e92-44dd-aafa-ba4fea982cc3.png)

**Comment by e271828-** [comment]
@MBNChannel looks like this is with the WPForms native hCaptcha integration, so you should open a ticket with their support.
