### ISSUE TITLE
Please add support to Wordpress post/page password-protect

### ISSUE THREAD

**Issue by sonalvrioss-svyatos** [hCaptcha/hcaptcha-wordpress-plugin#168]
Hi, is it possible to add hcaptcha to Wordpress post/page password-protect? I would like to restrict some posts/pages with the password-protect function but can't find any hcaptcha-enabled plugins to provide additional security. Thanks in advance.

**Comment by hollen9** [comment]
You dev team are great!
I also want this feature so bad. 👀

**Comment by kagg-design** [comment]
Added in v2.1.0.
