### ISSUE TITLE
wc_add_notice in woocommerce checkout provoking incorrect "The Captcha is invalid." error message

### ISSUE THREAD

**Issue by samsebree** [hCaptcha/hcaptcha-wordpress-plugin#169]
I have integrated this plugin and put it in front of our woocommerce checkout.
All is going generally well, but I am experiencing an issue. Here are the steps to repro:

1. Navigate to checkout page, fill out all checkout fields and complete the hCaptcha
2. Click "place order" and the checkout page will stop the checkout by throwing a wc_add_notice() error. This can be provoked in a number of ways. You can skip entering a mandatory field such as an email. On my site, we have some custom validation that throws wc_add_notice() errors on checkout. Anything works.
3.  Fix the checkout field which provoked the error. At this point, hCaptcha will still have a green checkmark indicating that the captcha is still valid.
4. Click "place order". hCaptcha will throw "The Captcha is invalid." despite having a green check mark indicating that the captcha is still valid. 

On my site, the only way to fix and get through the checkout is to either wait for the captcha to expire or refresh the page and start over.

Any tips to remedy this issue on my end would be much appreciated. My desired functionality would be to have the initial successful hCaptcha validation continue to be valid for the next form submit.

**Comment by samsebree** [comment]
Sorry to be a pest with this. @e271828- Were you able to repro this bug on your end?
Please let me know if there is anything I can do to help resolve this.

**Comment by pauldowlin** [comment]
I too have this same issue. Complete the captcha. Forget to fill in some required input box or checkbox. Fix that issue and hCaptcha throws invalid error when form is submitted again. 

Only fix is to refresh the page.

**Comment by e271828-** [comment]
@kagg-design do you have time to look at this?

**Comment by kagg-design** [comment]
@e271828- sure, I will.

**Comment by kagg-design** [comment]
Fixed in v1.18.0.
