### ISSUE TITLE
Elementor Pro (3.7.2) with hCaptcha (1.16.0)

### ISSUE THREAD

**Issue by MarkWest2017** [hCaptcha/hcaptcha-wordpress-plugin#170]
Hi,
Similar to this issue: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues/162

I do not see hCaptcha available to select in form fields.

![Screenshot_237](https://user-images.githubusercontent.com/25922969/176708621-c8d0a4d2-5c7f-49dd-9122-5f5cb6ddcd72.jpg)

WP: 6.0
Elementor: 3.6.6
EPro: 3.7.2
hCaptcha 1.16.0

Thanks for your help.
Kind Regards
Mark

**Comment by MarkWest2017** [comment]
Hi,
I'd really appreciate an update on this please.
I see someone else had logged a similar issue, that you were unable to replicate.
I'd be happy to perform fault-finding/debugging as I seem to be experiencing the same issue - no hCaptcha widget is showing as available to add to the EPro form.
Thanks
Mark

**Comment by MarkWest2017** [comment]
Hi,
To add a little more detail - I've tried this plugin on a different site - same WP/Elementor/EPro version and it seems to work (shows hCaptcha widget in Form builder).
So, on the site where it's not working I've disabled all plugins apart from Elementor/Elementor Pro and hCaptcha - still doesn't work.
On the site where it works I'm using Astra Pro theme,  on the site where it doesn't I'm using Kadence.
I'm going to try building a quick test site to test switching between the themes to see if I can isolate what might be causing the problem.
Kind Regards
Mark

**Comment by MarkWest2017** [comment]
Hi,
Ok, so built a completely fresh new WP install - 6.0.1, Elementor 3.6.7 and EPro 3.7.2 - so, exactly the same versions as the sites that do/don't work.
On this simple build I can't get it to work with either Kadence or Astra :/ - when I click to edit the form (I built before adding the hCaptcha plugin) I just get a grey left sidebar - image attached with either theme enabled.  This is the same as I'm getting on the site that doesn't work right now (Kadence theme).  If I deactivate the hCaptcha plugin I can edit the form again.
I've enabled wp-debug and when I have the hCaptcha plugin enabled I also get a bunch on notices above the editor and above the form - screenshot attached.  I'm unable to edit the form with wp-debug=true - there's simply no edit button showing for the element.
I'd be happy to provide a login for your to take a look if this will help - it's very odd.
Thanks
Kind Regards
Mark
![Screenshot_263](https://user-images.githubusercontent.com/25922969/180480187-4f7794ce-7be9-4bea-87fd-229ea2ae3bae.jpg)
![Screenshot_262](https://user-images.githubusercontent.com/25922969/180480145-71dd6c48-9e68-49bf-b87e-75a6dd521849.jpg)

**Comment by kagg-design** [comment]
Thank you, @MarkWest2017, for your investigations. Could you provide me access to the test site? Please send it to the email info@kagg.eu.

**Comment by Mark-Jdr** [comment]
Hello.
I think I have exactly the same (or a similar) problem. I am using Elementor Pro.
I installed the hCAPTCHA plugin and checked the "Enable hCaptcha on Elementor Pro Form" checkbox.
After adding the Elementor Form widget to a page, the entire Elementor settings panel on the left side of the screen disappears. Exactly as in the attached picture and same as the last included screen from MarkWest2017.

![hcaptcha-screen-01](https://user-images.githubusercontent.com/112420055/187262524-997e9dd5-366e-470f-961a-36e375493c78.JPG)

I am testing it on a very simple website that only has 3 plugins: Elementor, Elementor Pro and hCaptcha.
The parameters of my WP installation are as follows:
- Wordpress 6.0.1
- Theme: Twenty Seventeen - I also tested with Twenty Twenty-One
- Plugins - only 3:
  - Elementor     - v. 3.7.3   (the latest)
  - Elementor Pro - v. 3.7.4   (the latest)
  - hCaptcha      - v. 1.18.0  (the latest) 
- Linux / LiteSpeed
- MySQL - MariaDB Server v10.4.24
- PHP   - 7.4.29
- PHP Memory Limit: 1024M
- PHP Max Input Vars: 10000

Perhaps the parameters of my installation will help you find a solution.
Regards, Mark

**Comment by kagg-design** [comment]
@MarkWest2017 @Mark-Jdr Deactivate all Experiments in Elementor. Make sure there are no green lights to the left:

![image](https://user-images.githubusercontent.com/28291450/187286182-de24db0b-6e2b-4d76-a615-09f5c416edd2.png)

Here is the result on the test site after deactivation: [https://hcaptcha-dauntlessstudio-co-uk.dauntlessstudio.co.uk/hcaptcha-form-test-page/](https://hcaptcha-dauntlessstudio-co-uk.dauntlessstudio.co.uk/hcaptcha-form-test-page/)

**Comment by kagg-design** [comment]
Exactly, the Additional Custom Breakpoints setting is the culprit:

![image](https://user-images.githubusercontent.com/28291450/187287394-5f38100c-9b7a-4f70-bdb8-5498bcb601bd.png)

Without it, having all other experiments active, hCaptcha works:

![image](https://user-images.githubusercontent.com/28291450/187287736-9555b113-7f59-4cce-9803-4eb7ff097398.png)

**Comment by MarkWest2017** [comment]
Hi Igor,
Good to identify the issue - but we use all six breakpoints on our projects.
So, how to resolve incompatibility?
Thanks very much
Mark

29 Aug 2022 21:01:07 Igor at KAGG Design ***@***.***>:

**Comment by Mark-Jdr** [comment]
Disabling just one 'experiment' (Additional Custom Breakpoints) makes the Elementor settings of the Form having hCaptcha work again. Thank you for help. M.

**Comment by kagg-design** [comment]
@MarkWest2017 @Mark-Jdr Thank you guys, and especially @MarkWest2017, for your help in identifying the issue! I have fixed it in v1.19.0, and I hope we can release it today, 30-Aug.
