### ISSUE TITLE
Not receiving emails from form and hcaptcha endless spinning

### ISSUE THREAD

**Issue by ghost** [hCaptcha/hcaptcha-wordpress-plugin#172]
Why aren't I receiving emails from the form WPForm? hcaptcha also spins forever when I hit submit form on tests.

Thank you!

**Comment by e271828-** [comment]
Hi, got an example URL for this, or a way to reproduce?

**Comment by e271828-** [comment]
Also, @BrianT777 are you using the WPForms native hCaptcha support, or this plugin?

**Comment by kagg-design** [comment]
Closed as non-reproducible.
