### ISSUE TITLE
Form keeps hanging / spinning circle after submitting

### ISSUE THREAD

**Issue by Eastbourneshutters** [hCaptcha/hcaptcha-wordpress-plugin#177]
Hi, i have installed hcaptcha on my wordpress website https://eastbourneshutters.co.uk where i have 3 forms on wpforms, i have installed the plugin and set up the sitekey and secret key, enabled the hcaptcha in wpforms, but still it just hangs with a spinning circle.

Thanks for any help . .

**Comment by e271828-** [comment]
@Eastbourneshutters do you happen to have a test page? And are you using the built-in WPForms hCaptcha support? If so, you should contact WPForms directly.

**Comment by kagg-design** [comment]
Closed due to no response.
