### ISSUE TITLE
hCaptcha not showing up on Contact Form! 

### ISSUE THREAD

**Issue by steffi-blackphoenix** [hCaptcha/hcaptcha-wordpress-plugin#178]
Hello! 

I wanted to know, why my hCaptcha on my contact site doesn’t work.
https://diekunstdeslebens.at/kontakt/
I want it under the contact form 7, I checked it on the backend, but still doesn’t work.
I made the steps that were in the docs, it doesn't really help. 

Please help!

**Comment by kagg-design** [comment]
Please try to deactivate all plugins except hCaptcha and CF7. First, one named Nitro. Also, please switch the theme to standard and let me know the result.

**Comment by kagg-design** [comment]
Closed due to no response.
