### ISSUE TITLE
enable Pro Elements

### ISSUE THREAD

**Issue by zafai** [hCaptcha/hcaptcha-wordpress-plugin#186]
We are using the free version of elementor pro called pro elements.

Would be great if we could enable hcaptcha also for pro elements.
https://proelements.org/

Thank you

**Comment by kagg-design** [comment]
I am not sure what the plugin is, or who is behind it. Why it is free but not on wp.org?  I assume it is because it breaks some copyrights of Elementor. I would rather decline your proposal to support such a software.

**Comment by zafai** [comment]
@kagg-design all the copyright information are provided on there website:

PRO Elements is a derivative work from the Elementor Pro WordPress plugin by Elementor Ltd.

Like the original, it is licensed under the [GNU General Public License, version 3](https://www.gnu.org/licenses/gpl-3.0.html) (GPLv3).
But unlike the original, it is 100% free and does not require the activation to use it.

You are free to use, modify, and redistribute it. In other words, you are free to use the [essential freedoms](https://www.gnu.org/philosophy/free-sw.html) granted under the terms of the GPLv3 license.
