### ISSUE TITLE
Plugin name in ReadMe / WordPress.org Plugin Directory differs from installed Plugin name

### ISSUE THREAD

**Issue by timbutler** [hCaptcha/hcaptcha-wordpress-plugin#188]
Not sure if there's a reason the names differ, but when you search for the plugin to install it's called "hCaptcha for WordPress" (ie, what's in the ReadMe).

After it's installed, this is now "hCaptcha for Forms and More", which doesn't quite seem the same. My preference is hCaptcha for WordPress as it covers significantly more than just forms.

I know this is only a minor thing, however would it be better to have consistent naming to make it easier when providing instructions for users.

**Comment by e271828-** [comment]
Not sure what impact changing it would have at this point, since that would also update the URI on wordpress.org. @kagg-design thoughts?

**Comment by kagg-design** [comment]
@e271828- we cannot change slug on wp.org; https://wordpress.org/plugins/hcaptcha-for-forms-and-more/. It is a constant attribute of a plugin. To change it, we have to close the current plugin and publish it with a new slug, losing all subscribers.

As far as I can see, what @timbutler is talking about, is the name of the plugin on Plugins page:

![image](https://user-images.githubusercontent.com/28291450/190849129-b0a70514-60a7-4b81-8354-579b3b611813.png)

This is taken from the header of the main plugin file hcaptcha.php. And I think we can change it. At least [Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/) do not contain restriction to it. And FAQ says we can [change the plugin name](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#can-i-change-my-plugins-url-slug).

I will do it in v2.0 of the plugin, planned for release at the end of September.
