### ISSUE TITLE
No Integration with Security Plugins

### ISSUE THREAD

**Issue by waldemarker** [hCaptcha/hcaptcha-wordpress-plugin#190]
Hi, hcaptcha is great, but it would be very useful if compatible with wordpress security plugins like Wordfence or Security Pro.

**Comment by e271828-** [comment]
@waldemarker what kind of integration would you like to see?

**Comment by waldemarker** [comment]
you can use hcaptcha on woocommerce and when collecting data using a contact form, but you could use hcaptcha also when loggin in. Both security plugins use Google reCaptcha when logging in and it's very important (much more than the other uses).  As I'd like to use only 1 Captcha tool like hcaptcha I have the problem that both security plugins do not support that. For both plugins hCaptcha seems not to be relavant enough.

**Comment by kagg-design** [comment]
Wordfence has the option to use reCaptcha. It is on the page `/wp-admin/admin.php?page=WFLS#top#settings`.

![image](https://user-images.githubusercontent.com/28291450/192140143-de908ccd-d8ed-4095-afb5-a72968fd8c46.png)

Deactivate it. Or, deactivate hCaptcha by clearing the checkbox "Enable hCaptcha on Login Form".

**Comment by waldemarker** [comment]
thank you for the documentation. My goal is to leave google services and to switch to hcaptcha, so I would need hcaptcha in Wordfence or Security Pro instead of reCaptcha. Seems not possible at the moment and plugin authors are not interessed due to less security/compatibility with hcaptcha.

**Comment by kagg-design** [comment]
> My goal is to leave google services

I do not understand why you cannot just disable reCaptcha in Wordfence.

**Comment by waldemarker** [comment]
yes, this is true. I can disable on both plugins reCaptcha. And I'd like to use/install hCaptcha for that (login). Wondering that I get no help to make hCaptcha more popular here.

**Comment by kagg-design** [comment]
hCaptcha supports WordPress Login, Registration, Lost Password, Comment forms and many plugins: https://wordpress.org/plugins/hcaptcha-for-forms-and-more/#:~:text=FORMS%20AND%20PLUGINS%20SUPPORTED.

You should simply activate hCaptcha on these pages using the settings page.
