### ISSUE TITLE
how to set new data-h-captcha-id when using transition page plugin (swup.js)

### ISSUE THREAD

**Issue by mancu89** [hCaptcha/hcaptcha-wordpress-plugin#191]
I am working to a project in Wordpress and I'm trying to add h-captcha control to a form that is inside the swup container (it is the element that change on the transition while the header and footer remain the same).
By inspecting the code a data-h-captcha-id attribute is set on the first load of the page, the issue starts when i leave and return to the page that contains the form as the data-h-captcha-id attribute is missed and the h-captcha doesn't work.

Does anyone else used h-captcha plugin for Wordpress  with the swup.js script installed?
Is there a method to set a new data-h-captcha-id  for the Wordpress plugin?

**Comment by e271828-** [comment]
Do you have a demo page?

**Comment by kagg-design** [comment]
Closed as non-reproducible.
