### ISSUE TITLE
Gravity forms not work with hCaptcha

### ISSUE THREAD

**Issue by EntremCoop** [hCaptcha/hcaptcha-wordpress-plugin#194]
Hi,
 
Currently, I use hCaptcha on my WordPress website.
The thing is that I have a multi-page form made with Gravity Forms and when I fill in the data and click Next it keeps thinking.
If I use the browser inspector, the console gives me the following in the POST method: error "403".
It seems that the integration between hCaptcha WordPress plugin and Gravity Forms caused the issue.
The problem is that the 403 happens while calling the URL that have the form via POST method. 
If I deactivate my WordPress plugin there is no problem and everything works normally, could you tell me a solution?
 
Thank you!

**Comment by kagg-design** [comment]
This functionality is added in v2.1.0 and will be published soon.
