### ISSUE TITLE
Didn't work : block hCaptcha on specific page

### ISSUE THREAD

**Issue by Guiver** [hCaptcha/hcaptcha-wordpress-plugin#199]
Kaggdesign ask me to create an issue here (initially posted on wordpress plugin support  : https://wordpress.org/support/topic/filter-hcap_activate-didnt-work/#post-16129536 )

Sorry for my English.

I'm up to date (Wordpress 6.03)
My theme is OceanWP. I'm using Elementor (free) and polylang.
I haven't plugin for cache or security.
I'm actually on localhost (I follow the hcaptcha guide here : ( https://docs.hcaptcha.com/#local-development )
I have a free hcaptcha account.

The problem :
When I add the function and the add_filter describe to the FAQ on my theme's functions.php, this function never execute.( https://wordpress.org/plugins/hcaptcha-for-forms-and-more/#how%20to%20block%20hcaptcha%20on%20specific%20page%3F )

I can see this because when I had a var_dump and a console.log at the top of the function, I never see them.

Strangely, when I add the function for "How to show hCaptcha widget instantly? ", this function is working. When I add the var_dump and console.log at the top of this function, I see them.
This function is very similar to the other.

I verify if I had already a function "my_hcap_activate" or "hcap_activate" on all my Worpress files but I haven't.

I didn't undestand this problem.

**Comment by kagg-design** [comment]
Thank you for creating the issue.

Are `hcap_activate` and `hcap_delay_api` filters in the same file? Could you publish this file somewhere?

Or, can you create a copy of your local test site with the Duplicator plugin (after deletion of all personal data) and share it with me via info@kagg.eu email? In this case, I will debug the issue locally.

**Comment by kagg-design** [comment]
Closed as non-reproducible.
