### ISSUE TITLE
hcaptcha is not defined // Elementor Form

### ISSUE THREAD

**Issue by Pixelharmonist** [hCaptcha/hcaptcha-wordpress-plugin#202]
Hey There! 

The newest issue ist a "hcaptcha is not defined" notice, if i use hcaptcha in Elementor (pro).

![image](https://user-images.githubusercontent.com/69324212/200108440-5695caa6-419a-45e9-9449-a1756c5e2d2d.png)

After submit it throw back to top of the page(s) without sending.

If i turn off the integration and insert the hcaptcha shortcode into a Elementor html-field, the form is sendable without checkboxing hcaptcha...

One of relevant Websites: https://gruenderschmiede.org/kontakt-formular-anfahrt/#formular (german language)
Actual is the version with HTML + Shortcode inside

How can i solve it?

**Comment by Pixelharmonist** [comment]
The Support says: "Try the Shortcode"
It was done bevor i wrote. The Shortcode let send the Form without checking the hcaptcha-box. 

Anyone a idea for the script problem?

**Comment by massimocoladarci** [comment]
Hi, I have the same issue.

**Comment by massimocoladarci** [comment]
I reverted my plugin to 1.19.0 and it worked.

**Comment by Pixelharmonist** [comment]
Grazie Massimo! 

At first, i was happy for you and happy to read it... 
I tryed it out, rerolled the version but the only change was "there is no error in console". 
New: recaptchacompat disabled
![image](https://user-images.githubusercontent.com/69324212/200189396-4652ab82-92da-4af2-9883-f94baca6abd4.png)

How do you insert hCaptcha in your Form? Shortcode? Setting insert? 
I tested it both, with no succsess....

**Comment by massimocoladarci** [comment]
I'm sorry but i made a mistake, i still have the same issue...

**Comment by hansdampf110** [comment]
Same here:
Added hCaptcha as plugin.
Added field *hCaptcha* in Elementor Form.
hCaptcha shows riddle but after check, form is not send and got throw back on top of page.
Also tried hCaptcha plugin 1.5.0.

Current setup:
WP 6.1
Elementor 3.8.0
Elementor Pro 3.8.1
hCaptcha 2.0.0

**Comment by kagg-design** [comment]
@Pixelharmonist @massimocoladarci @hansdampf110 Thank you for the report. The problem is that in the latest versions, Elementor changed the sequence of JS hooks.

I have fixed it in v2.1.0. It will be published in a few days. Or, you can get it from the v2.1.0 branch.

**Comment by Pixelharmonist** [comment]
Hey @kagg-design! 

It runs cleary! I appreciate you engagement! 
Thanky you so much!!! 🤩🤩🤩🤩🤩

**Comment by hansdampf110** [comment]
It is working again. Thank you so much!
