### ISSUE TITLE
Integration with Asgaros forum plugin

### ISSUE THREAD

**Issue by albanmosnier** [hCaptcha/hcaptcha-wordpress-plugin#203]
I am using successfully hcaptcha for WP Login and ContactForm 7. But due to numerous malicious post oi new topics attempts in my Asgaros forum, it would be great if hcaptacha would be integrated with it

**Comment by jhnpldng01** [comment]
I second the motion. Asgaros has just enough features while wpForo has too many

**Comment by kagg-design** [comment]
Done in v2.6.0, which will be released soon.
