### ISSUE TITLE
Add Otter Blocks Support

### ISSUE THREAD

**Issue by HardeepAsrani** [hCaptcha/hcaptcha-wordpress-plugin#209]
Add support for Otter Blocks' Form Block. PR can be found here: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues

It's been a required feature from few of our users.

**Comment by kagg-design** [comment]
Dear @HardeepAsrani, thank you for your contribution to the hCaptcha plugin! I have merged your PR in the v2.4.0 branch, which is scheduled for release at the end of December. Kindly let me know if you need it earlier.

Many thanks again.

**Comment by HardeepAsrani** [comment]
@kagg-design Thanks. You can release it whenever it fits best your release schedule.
