### ISSUE TITLE
Avada: hCaptcha placement broken with "Upload Field"

### ISSUE THREAD

**Issue by cheich** [hCaptcha/hcaptcha-wordpress-plugin#212]
When using Avadas "Upload Field" element, the captcha is placed directly after this instead of after the submit button.

Seems like this element is using the same filter hook: 'fusion_element_button_content'

<img width="649" alt="grafik" src="https://user-images.githubusercontent.com/5952533/210254514-23d19649-1a0c-4df7-b274-a9285a13a4e2.png">

**Comment by kagg-design** [comment]
Thank you for the report. Fixd in v2.4.0, which will be published soon.
