### ISSUE TITLE
Captcha + send in blue fails

### ISSUE THREAD

**Issue by nicleg** [hCaptcha/hcaptcha-wordpress-plugin#213]
Hi,

I installed hCaptcha WP plugin to switch from Google To hCaptcha.

I also installed Send In Blue plugin.

Things seems working on the front forms I've made, but it looks failing on sendinblue forms.

On hCaptcha plugin settings page, Send In Blue is enabled, and I can see the hCaptcha on my page in the form.
But, the hCaptcha checked/validated or not, the form is sent and I receive the confirmation's email from Send In Blue.

I previously thought I made a mistake on my Send In Blue newsletter form, but I tried with a new SIB form and its the same.

Send In Blue plugin make the form validation on its own, and I don't (think) have access to  it, so I can't try to validate the hCaptcha.

Is there something to do I missed ?

thank's,
Nicolas.

**Comment by e271828-** [comment]
@nicleg can you upload/link an example page?

**Comment by nicleg** [comment]
https://thela.fr

**Comment by kagg-design** [comment]
The hCaptcha plugin is not activated on the site - I cannot see and reproduce the issue. 
Can you make a copy of the site with hCaptcha plugin activated and give me access to this site copy?

Thank you.

**Comment by kagg-design** [comment]
Closed as non-reproducible.
