### ISSUE TITLE
Integration with GIVE WP would be awesome

### ISSUE THREAD

**Issue by rescueboy** [hCaptcha/hcaptcha-wordpress-plugin#218]
For now GIVE WP https://givewp.com/ is integrated only with reCaptcha but some captcha plugins have integration. Would be great that hCaptcha has also this option. Keep up the good work ! Thx

**Comment by kagg-design** [comment]
@rescueboy, Could you explain what actions I have to take with the plugin to see reCaptcha on the email access form? I have found reCaptcha settings in the admin, but what is the email access form and how to reach it?

Thank you.

**Comment by kagg-design** [comment]
Added to 2.6.0, will be released soon.
