### ISSUE TITLE
Proxying support for full GDPR compliance

### ISSUE THREAD

**Issue by RafaelKr** [hCaptcha/hcaptcha-wordpress-plugin#219]
In the recent past a company in Germany was fined due to using Google Fonts. The reason was that the IP address of website visitors is transmitted to Google and that violates Europe's General Data Protection Regulation (GDPR).
The full article can be found here: https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/

There's also an interesting discussion on reddit about hCaptcha where I found the link to that article.
https://www.reddit.com/r/ProtonMail/comments/w3rdvb/hcaptcha_is_a_gdpr_violation/

So by this definition loading any resources from external servers is a violation to the GDPR because the IP address is leaked, which also includes loading hCaptcha.

To circumvent the IP leaking to Google we now proxy the requests through our own servers. For some pages we're using nginx for proxying, for others we're using PHP.

It would be great to make proxying available in this plugin, so all resources are loaded through the host on which the WordPress page is hosted, not directly from hcaptcha.com (and some subdomains of hcaptcha.com). Maybe even enable it by default.
I'm not sure if this would compromise bot protection for example when setting "Passing Threshold" to "Auto" where "Difficulty varies based on metrics". But I'm pretty sure there is a way to proxy relevant data, e.g. the User Agent.

I would also be open to provide the PHP code we're using for proxying. The option to proxy directly via nginx would be even better, as that reduces the server load significantly. If you're open to discussion of this topic you can provide me a way to contact you, e.g. an email address.

**Comment by e271828-** [comment]
I don't believe this is relevant to a security service, which legitimately uses the IP address. https://docs.hcaptcha.com/faq#do-i-need-to-display-anything-on-the-page-when-using-hcaptcha-in-invisible-mode offers the following suggestion on privacy policy:

> You may also prefer to integrate a notice into your Privacy Policy similar to the following:

> hCaptcha

> We use the hCaptcha anti-bot service (hereinafter "hCaptcha") on our website. This service is provided by Intuition Machines, Inc., a Delaware US Corporation ("IMI"). hCaptcha is used to check whether the data entered on our website (such as on a login page or contact form) has been entered by a human or by an automated program. To do this, hCaptcha analyzes the behavior of the website or mobile app visitor based on various characteristics. This analysis starts automatically as soon as the website or mobile app visitor enters a part of the website or app with hCaptcha enabled. For the analysis, hCaptcha evaluates various information (e.g. IP address, how long the visitor has been on the website or app, or mouse movements made by the user). The data collected during the analysis will be forwarded to IMI. hCaptcha analysis in the "invisible mode" may take place completely in the background. Website or app visitors are not advised that such an analysis is taking place if the user is not shown a challenge. **Data processing is based on Art. 6(1)(f) of the GDPR (DSGVO): the website or mobile app operator has a legitimate interest in protecting its site** from abusive automated crawling and spam. IMI acts as a "data processor" acting on behalf of its customers as defined under the GDPR, and a "service provider" for the purposes of the California Consumer Privacy Act (CCPA). For more information about hCaptcha and IMI's privacy policy and terms of use, please visit the following links: https://www.hcaptcha.com/privacy and https://www.hcaptcha.com/terms.
