### ISSUE TITLE
v1.4.2 plugin installed from wordpress.org doesn't include assets

### ISSUE THREAD

**Issue by trolley** [hCaptcha/hcaptcha-wordpress-plugin#22]
Installing this plugin v1.4.2 through the built-in Wordpress plugin interface doesn't include the assets directory.

**Comment by e271828-** [comment]
Yes, looks like assets should be named plugin-assets or similar. The totality of its plugin-relevant contents is:

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/master/assets/styles.css

which is probably not making a huge difference either way.
