### ISSUE TITLE
Does not work anymore?

### ISSUE THREAD

**Issue by Tsjippy** [hCaptcha/hcaptcha-wordpress-plugin#221]
My hcaptcha does not load anymore.
All I get is the html below:

```
<div class="entry-content" itemprop="text">
    <div class="h-captcha" data-sitekey="MYSITEKEY" data-theme="light" data-size="normal" data-auto="false">
   </div>
   <input type="hidden" id="hcaptcha_nonce" name="hcaptcha_nonce" value="eca34e102a">
   <input type="hidden" name="_wp_http_referer" value="/simnigeria/testpage/">
</div>
```

I have tried it both as `do_shortcode( '[hcaptcha]' );` and adding the shortcode `[hcaptcha]` to page

**Comment by e271828-** [comment]
@Tsjippy can you provide more info on where/how you're using the shortcode, and ideally an example page?

**Comment by Tsjippy** [comment]
I tested it on my default website, where it was working before.
I also tried disabling all other plugins, and switching theme.

Nothing seemed to work.

I created an example page here: [url](https://simnigeria.org/hcaptcha_1/).
Thats just a blank wordpress page with a shortcode block containing the hcaptcha shortcode

**Comment by kagg-design** [comment]
To work, hCaptcha must be inside the <form ...>...</form> tag.

On your page, you have two hCaptcha divs: one is visible, and another one is in the hidden #hcaptcha-form. That div inside the hidden form is rendered successfully.

![image](https://user-images.githubusercontent.com/28291450/214851831-27d080e3-4a4a-4518-89f5-773b3ba4d5ec.png)

**Comment by e271828-** [comment]
@kagg-design maybe we should update the docs to clarify this for the shortcode.
