### ISSUE TITLE
PHP Warning: Undefined array key "step" SettingsBase.php on line 611

### ISSUE THREAD

**Issue by AbraxasDMG** [hCaptcha/hcaptcha-wordpress-plugin#222]
Hi.

Just installed the plugin today and found this warning in the php_error file.

I'm on wp v6.1.1, php v8.1 and hcaptcha plugin v2.4.0.

Thanks in advance!

**Comment by kagg-design** [comment]
Hi @AbraxasDMG, thank you for creating the issue. I have fixed it in v2.5.0. We will publish it in 1 week.
