### ISSUE TITLE
Wordpress Support < v6.1 with 2.5.0

### ISSUE THREAD

**Issue by drdrjojo** [hCaptcha/hcaptcha-wordpress-plugin#224]
Following Line killed the plugin support for Wordpress < v6.1:

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/b3eb144b37cf5ae7282e78383b42f5cbbfbb2322/src/php/Main.php#L413

did_filter  is a function added with Wordpress v6.1 and throws an error with v6.x or below:

>  PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function HCaptcha\did_filter() in /var/www/wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Main.php:413

**Comment by e271828-** [comment]
@drdrjojo PR welcome :)

**Comment by kagg-design** [comment]
Thank you for the report. I have fixed this bug in 2.5.1. We will publish it asap.
