### ISSUE TITLE
Integration with Advanced custom field (ACF)

### ISSUE THREAD

**Issue by Sebastian216** [hCaptcha/hcaptcha-wordpress-plugin#225]
We have ACFE Pro Integration I cant imagine a lot of people use ACF Pro and ACFE Pro (ACFE Needs ACF Pro)
Way better integration would be to add hcaptcha to ACF Pro as a new field type, there is one for reCAPTCHA.

Make it more versatile aswell.

**Comment by kagg-design** [comment]
ACFE allows the creation of a form. That is why it was used. The hCaptcha field cannot work outside of the form.

I do not see the workflow on how to create a form in admin with ACF PRO. Could you provide a screencast?
