### ISSUE TITLE
Version 2.5.0 crashes website

### ISSUE THREAD

**Issue by cptcreative** [hCaptcha/hcaptcha-wordpress-plugin#227]
Hi there,

I've recently had an issue with the plugin on a few of my websites. I made the update to the plugin from 2.4.0 > 2.5.0 and after that the plugin crashes the website. First off the layout of the site looks all wrong and I get my alerts telling me the site is down!

I login to the website, deactivate the plugin and all is well. I empty all caches and try again and the same thing happens. When I check the following error log in WooCommerce logs:

 CRITICAL Uncaught Error: Call to undefined function HCaptcha\did_filter() in /wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Main.php:413

And I get the following error log on the server:

Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function HCaptcha\\did_filter() in /wp-content/plugins/hcaptcha-for-forms-and-more/src/php/Main.php:413

Can you guys please take a look and see if an update to the plugin is required?

Thanks.

**Comment by kagg-design** [comment]
Thank you for the report. It was fixed in v2.5.1.
