### ISSUE TITLE
TypeError: function bound () { [native code] } is not a constructor

### ISSUE THREAD

**Issue by xxxmicrobexxx** [hCaptcha/hcaptcha-wordpress-plugin#228]
I am trying to incorporate hcaptcha into a wordpress plugin.

The js is loaded, but in dev tools console I see an error: ` hsw.js line 1 > Function:3:72849 `
`
TypeError: function bound () { [native code] } is not a constructor`

I assume that is the cause of there being no field element named h-captcha-response

The website is [https://pro.speakout.123host.net.au/  ](https://pro.speakout.123host.net.au/ )and is a test development site.

Thanks for any insights you can offer.

**Comment by kagg-design** [comment]
I see no issues on the site right now. Thank you.
