### ISSUE TITLE
Add polyfill for requestSubmit().

### ISSUE THREAD

**Issue by kagg-design** [hCaptcha/hcaptcha-wordpress-plugin#229]
https://wordpress.org/support/topic/issue-with-ajax-invisible-hcaptcha-older-browser/

closed in d98937b737f7653c1e9c594380ca4bc6f574a2a9

**Comment by dyamized** [comment]
This looks great.

**Comment by kagg-design** [comment]
@dyamized, thank you for communicating here. Did you test the solution?

**Comment by dyamized** [comment]
I'm not set up with composer. If you want to send me the build outputs, I could test that.

**Comment by kagg-design** [comment]
Please use this zip file: https://drive.google.com/file/d/1oDnHpABfYCMW3ksR-4CQ02-3qaIepf0C/view?usp=sharing

**Comment by dyamized** [comment]
Well, that just says 'requestSubmit' is not defined. It doesn't appear to have pulled in the polyfill.

**Comment by kagg-design** [comment]
Apologies, I forgot to add the import statement to the js file. Could you try the updated version: https://drive.google.com/file/d/1iaEllIyPxLL66wSxY7p6FDBbw1qz_dVW/view?usp=sharing ?

**Comment by dyamized** [comment]
Yes! That works. Thank you.

**Comment by kagg-design** [comment]
Thank you, @dyamized, for your help!

**Comment by dyamized** [comment]
The invisible hCaptcha keeps breaking on older Safari. It was fixed in the
one version where you said you fixed it, but after that it's been broken. I
tested 3.1 just now, and it doesn't work. I have to keep reverting to the
old version.

**Comment by kagg-design** [comment]
@dyamized, Could you provide a link to the page where invisible Captcha does not work with older Safari?

**Comment by dyamized** [comment]
Sure, here is one:

https://www.dragonframe.com/downloads/

(The form to download the trial.)

**Comment by kagg-design** [comment]
I need help understanding the issue. 

On my test website, I have created a form identical to yours: [https://test.kagg.eu/safari-14/](https://test.kagg.eu/safari-14/) and tested it with Safari 14. The site has hCaptcha 3.2.0 installed (no changes in the main hcaptcha.js file from 3.1.0). The form works well; I see that the invisible hCaptcha challenge is invoked, and the form is sent upon solving it.

No errors in the Safari console. Debugging JS, I see that `https://test.kagg.eu/wp-content/plugins/hcaptcha-for-forms-and-more/assets/js/apps/hcaptcha.js?ver=3.2.0` on line 186 executes t.submit(), not t.requestSubmit(e). And it is OK because Safari 14 does not support `requestSubmit`.

I tried to log in on the same site with Safari-14: [https://test.kagg.eu/wp-login.php](https://test.kagg.eu/wp-login.php). The login form also works well.

Could you explain what kind of troubles you have with hCaptcha 3.2.0 and Safari-14? Thank you.

**Comment by dyamized** [comment]
You wrote: "on line 186 executes t.submit(), not t.requestSubmit(e). And it
is OK because Safari 14 does not support requestSubmit."
But that is the issue, and why originally you fixed this bug by adding a
polyfill for 'requestSubmit'. They work differently.
https://wordpress.org/support/topic/issue-with-ajax-invisible-hcaptcha-older-browser/
I have added a submit event handler to send the form via Ajax, and this
doesn't get triggered if you use 'submit()'.

**Comment by kagg-design** [comment]
We had some conflicts with fixing this issue via polyfill. That is why we reverted the fix.

The plugin works now with Safari 14. 

If you expect requestSubmit() polyfill in Safari 14, I believe you should add the polyfill to your code. Thank you.
