### ISSUE TITLE
No captcha on Jetpack contact form

### ISSUE THREAD

**Issue by trolley** [hCaptcha/hcaptcha-wordpress-plugin#23]
I manually installed v1.4.2 from the release pages of this repo and enabled it on Jetpack contact form but it does not appear, and the form no longer works.

I'm using Wordpress version 5.4.1 and Jetpack 8.4.2.

Please let me know what types of logs or anything I can provide. I'm not super familiar with Wordpress so I'm not sure where to get useful logs for an issue like this.

**Comment by e271828-** [comment]
Let me know if this is still happening. Should be resolved in the latest version.

**Comment by trolley** [comment]
It is still happening. I’m on Wordpress 5.4.2 with hCaptcha 1.5.1 and JetPack 8.6.1. It’s working on the login page, but on the page with the Jetpack contact form it doesn’t appear and the form doesn’t work if hCaptcha is enabled on it; submitting just redirects back to the form page and the message isn’t received.

**Comment by KennyStier** [comment]
I too seem to be having issues with hCaptcha on the Jetpack contact form. It works in the other spaces where I have it enabled.

**Comment by antonywu** [comment]
I am reporting the same issue with Wordpress 5.5.3, hCaptcha 1.6.3, and JetPack 9.0.2
The JetPack Contact Us form doesn't appear to have the hCaptcha present even though it does seem to block message from being sent. (makes senses as the form fails the hCaptcha in the background, but user has no way of seeing the hCaptcha in the first place)

**Comment by e271828-** [comment]
@kagg-design can you take a look?

**Comment by kagg-design** [comment]
@e271828- I see, it does not work with Block Editor. With Classic Editor, it works. Adding a code...

**Comment by kagg-design** [comment]
@e271828-  https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/54

**Comment by e271828-** [comment]
@antonywu @KennyStier can you please try out https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/54 and let us know if that solves your issue?

**Comment by KennyStier** [comment]
@e271828- @kagg-design  #54 Solved my issue. Thanks
