### ISSUE TITLE
Moving hCaptcha on checkout page

### ISSUE THREAD

**Issue by JohnBob01** [hCaptcha/hcaptcha-wordpress-plugin#235]
I would like to move hcaptcha on my checkout page.  It currently sits
below billing address info and I would like it right above 'Place order'
button.
Customers are doing the hcaptcha verification, then by the time they
enter card info and place order, it has expired and they have to do it
again.
I see no way to move it and Woocommerce shows no way to rearrange page.
Thanks for your help,

**Comment by kagg-design** [comment]
I have moved the hCaptcha badge to the location above the Place Order button. It will be released in 2.7.0 at the beginning of April.

**Comment by JohnBob01** [comment]
Thank you so much!  This problem has been bugging me for a long time.
