### ISSUE TITLE
PMPro Support?

### ISSUE THREAD

**Issue by TheRayJohnson** [hCaptcha/hcaptcha-wordpress-plugin#240]
Howdy!

Possible to support Paid Memberships Pro/PMPro? The free version.

[GitHub](https://github.com/strangerstudios/paid-memberships-pro) | [WordPress Plugin Home](https://en-gb.wordpress.org/plugins/paid-memberships-pro/)

**Comment by kagg-design** [comment]
Added in v2.10.0. It will be released in July.
