### ISSUE TITLE
Please Add Support for the Divi Email Optin Form Module

### ISSUE THREAD

**Issue by meximan** [hCaptcha/hcaptcha-wordpress-plugin#244]
I see you already have Divi support for the Divi comment,  Divi contact form, and Divi Login Form.

Please add hCaptcha support for the Divi Email Optin Form Module.

https://www.elegantthemes.com/documentation/divi/newsletter/

I dislike using Google.

**Comment by kagg-design** [comment]
Done in v2.9.0, will be released in days.
