### ISSUE TITLE
WordPress and WooCommerce settings "interfere"

### ISSUE THREAD

**Issue by joostdekeijzer** [hCaptcha/hcaptcha-wordpress-plugin#245]
On my network-install site with WooCommerce enabled I have the following issue.

WooCommerce sets the "forgot password" link to their "password reset" page.

When I enable the WordPress "password reset" form but **don't** enable the WooCommerce "password reset" form, the end result is that:

1. I don't get the hCaptcha test on my "password reset" form **but**
2. On submit the form fails because I did not complete my hCaptcha test

So somewhere the WooCommerce setting is used for generating the form but the WordPress setting is used when validating the form.

Eg. the WooCommerce login form does not have this ussue.

Tested (on a WordPress network install) v6.2 with hCaptcha v2.8.0

**Comment by kagg-design** [comment]
Thank you for the report. The bug is fixed in v2.9.0, to be published at the end of May.
