### ISSUE TITLE
Back In Stock Notifier for WooCommerce support

### ISSUE THREAD

**Issue by kagg-design** [hCaptcha/hcaptcha-wordpress-plugin#246]
The plugin “[Back In Stock Notifier for WooCommerce](https://wordpress.org/plugins/back-in-stock-notifier-for-woocommerce/)“ is currently the best and most complete Woocommerce Waitlist plugin. But natively, it is only compatible with reCaptcha.

How about adding compatibility to this plugin as well?

https://wordpress.org/support/topic/compatibility-with-back-in-stock-notifier-for-woocommerce-2/

**Comment by lgdelai** [comment]
Thank you @kagg-design 
I Will follow this topic.

**Comment by kagg-design** [comment]
I have added support for the plugin. It got some effort... The codebase of the plugin and its hook system are far from optimal.

Anyway, now it works and will be released next week with v2.9.0.

**Comment by lgdelai** [comment]
Thank you @kagg-design 
Have a nice week

**Comment by lgdelai** [comment]
Hello.  @kagg-design 

I enabled the option in the Hcaptcha settings, but the hcaptcha was not displayed in the back in stock notifier.

Do I need to do any other procedure to activate?

**Comment by kagg-design** [comment]
Which option did you use - this one?

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/7d63929e-96fe-4382-8301-3d9dc647479c)

When it is activated, you should see the following when the product is out of stock:

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/49e99af7-2791-4925-9677-cc2b61398a5b)

**Comment by lgdelai** [comment]
Thanks for the feedback.  

I found out the reason, the "disable when logged in" option was enabled in hcaptcha.  

But I discovered a problem while testing.  

The captcha is never available to click when it is displayed in the popup form (The popup is displayed when we click the button, from the product listing screen of the store "not the single product" ).

![Screenshot_20230613_204522](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/7806314/0454598b-e5af-4753-bfba-9eb388176f43)

**Comment by kagg-design** [comment]
It is not a bug, but the absence of the feature. I did not know that button can be added on the shop page. Will work on it.

**Comment by lgdelai** [comment]
Ok, 

let me know when you make the adjust to make a new test. 

Thanks

**Comment by lgdelai** [comment]
Hello @kagg-design 

Do you have any news about this case?

Thanks.

**Comment by kagg-design** [comment]
Added in v2.10.0 and will be released in July.

**Comment by lgdelai** [comment]
I just tested it and now it's working perfectly.

Thank you and congratulations for the excellent work!
