### ISSUE TITLE
Safari 14/15 and invisible hCaptcha leads to looping challenge

### ISSUE THREAD

**Issue by dyamized** [hCaptcha/hcaptcha-wordpress-plugin#247]
We have hCaptcha enabled for our WooCommerce registration page and a free trial page (using shortcode + server code).
This has been working well.

Recently we've had a couple users say that on Safari, the hCaptcha keeps challenging them.
I did some testing, and this is true, when we are using the 'invisible' mode.

It seems fine in Safari 16, but this issue happens in Safari 14.x and 15.x.

Woo registration (right-side form):
https://www.dragonframe.com/my-account/

Download/Free-Trial form:
https://www.dragonframe.com/downloads/

I don't see any console errors. When hCaptcha is invisible, you complete the challenge, and then it starts over, instead of submitting the form. If I switch hCaptcha to normal/compact, it works fine.

**Comment by dyamized** [comment]
I have fixed the issue on my site, but you should be able to reproduce it on a site with WooCommerce.

It looks like the issue was caused by this change to hcaptcha.ja in V2.8.0:
[src/js/hcaptcha/hcaptcha.js](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/commit/7e5280eff65c765ff06ac1fd45ec23706178d285#diff-1cdc39dac6c5be402271d45a8312aecf2481deaa321b99009b9bb7861630b5e3)

**Comment by kagg-design** [comment]
Thank you for the report. The issue had a bit different nature, but yes, it related to the submit(). Fixed and tested in Safari 14-16 and Chrome.

It will be published in days with 2.9.0.
