### ISSUE TITLE
Contact Form 7 hCaptcha Broken

### ISSUE THREAD

**Issue by Electromaster232** [hCaptcha/hcaptcha-wordpress-plugin#25]
Hello,

I am using this plugin along with Contact Form 7 on my WordPress site. When I look at the form, I see and can fill out the hCaptcha, however I cannot submit the form, getting this response in my network tab to the submit request (and yes I did fill out the captcha before attempting to submit):

`{"into":"#wpcf7-f5655-p3397-o1","status":"validation_failed","message":"One or more fields have an error. Please check and try again.","invalidFields":[{"into":"span.wpcf7-form-control-wrap.hcap_cf7-h-captcha-invalid","message":"Invalid captcha","idref":null}]}`

No error logs are generated server-side. I have no idea how to troubleshoot this issue because of that.
Looking at the code for the cf7 integration, I cannot see where the error "Invalid captcha" appears. I can see "Please complete the captcha." and "The Captcha is invalid." but not invalid captcha, which makes me wonder if the error is being generated on the remote end.

Thank you for your help.

**Comment by e271828-** [comment]
Hi, I'm not certain if that's an error message from the server, but you can try dropping some log statements into the PHP in order to see what the server is returning.

**Comment by Electromaster232** [comment]
Hello,

I added the following lines to both hcaptcha.php and hcaptcha-cf7.php
```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```
These are obviously only going to log code errors and not log the responses, and did not affect the output when submitting the form. What logging lines would you recommend so I can see what its doing?

Thanks

**Comment by e271828-** [comment]
> Hello,
> 
> I added the following lines to both hcaptcha.php and hcaptcha-cf7.php
> 
> ```
> ini_set('display_errors', 1);
> ini_set('display_startup_errors', 1);
> error_reporting(E_ALL);
> ```
> 
> These are obviously only going to log code errors and not log the responses, and did not affect the output when submitting the form. What logging lines would you recommend so I can see what its doing?
> 
> Thanks

Looks like: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/e2f203f5556785d1074c98d8aa388e928870a70d/common/request.php#L17
is the place you want to log. Seeing `$body` will tell you what's going on.

**Comment by e271828-** [comment]
Should now be resolved.

**Comment by HammyHavoc** [comment]
Getting this issue too.
