### ISSUE TITLE
Contact Form 7 nonce

### ISSUE THREAD

**Issue by ktmn** [hCaptcha/hcaptcha-wordpress-plugin#250]
I had a contact form fail. The `/wp-json/contact-form-7/v1/contact-forms/123/feedback` REST request responded:

```
{
    "code": "rest_cookie_invalid_nonce",
    "message": "Cookie check failed",
    "data": {
        "status": 403
    }
}
```

The page was minifed with Autoptimize and also cached with Cache Enabler. The session was in incognito window, not logged in.  The `<input type="hidden" id="_wpnonce" name="_wpnonce" value="..." />` value was probably expired, hence the error.

While the solution is to disable caching on the page with the form, I manage a lot of sites and this issue is very hard to reproduce. I've always been able to cache the contact pages, but I guess not, not with hCaptcha enabled at least.

So this begs the question, why is there a nonce in the first place? Is it required for hCaptcha, since CF7 itself doesn't have it.

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/3367397da8c4a121023c3f1eec5c71baeb8093ce/src/php/CF7/CF7.php#L101-L104

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/3367397da8c4a121023c3f1eec5c71baeb8093ce/src/php/CF7/CF7.php#L173

Maybe it's not necessary and only causes head ache of unexpected failures.

**Comment by kagg-design** [comment]
Nonce provides an additional level of security and should be used. To avoid problems with nonce here and in other forms, the cache time should be less than nonce time (24 hours).

**Comment by ktmn** [comment]
> the cache time should be less than nonce time (24 hours)

That can still leave a window where the form is not functional if the cache was created shortly before the nonce rotated. So there can not be a cache.
