### ISSUE TITLE
Integration with Classifieds Listing Plugin

### ISSUE THREAD

**Issue by recruitersassociation** [hCaptcha/hcaptcha-wordpress-plugin#251]
Classifieds Listing Plugin does not have integration with H Captcha
https://www.radiustheme.com/ 
Please provide HCaptcha integration option 
Cause we do not want to use Google and HCaptcha  together we want to use only one captcha 
which is HCaptcha

**Comment by kagg-design** [comment]
Added in v2.10.0, will be released in days.
