### ISSUE TITLE
Please add Affiliates Support

### ISSUE THREAD

**Issue by recruitersassociation** [hCaptcha/hcaptcha-wordpress-plugin#256]
Kindly add HCaptcha Integration for Affiliates Plugin Form and login page.

https://wordpress.org/plugins/affiliates/

**Comment by kagg-design** [comment]
The plugin https://wordpress.org/plugins/affiliates/ has a few active installs (4,000+). We added your request to the queue but cannot guarantee when we can resolve it. Thanks.

**Comment by kagg-design** [comment]
Added to 3.6.0. To be released early in Jan.
