### ISSUE TITLE
Add support for Elementor Essential Addons

### ISSUE THREAD

**Issue by kagg-design** [hCaptcha/hcaptcha-wordpress-plugin#257]
[wp.org ticket](https://wordpress.org/support/topic/trying-to-submit-form-without-entering-captcha-throws-error)

**Comment by asmittle** [comment]
Hi @kagg-design, following up so I'll get updates on this item. Thanks!

**Comment by kagg-design** [comment]
The problem was in Gravity Forms Ajax forms by itself. I have added support for GF Ajax, and on the test page created with Essential Addons, the Ajax GF form also works.

Plugin version 3.0.0 will be released at the beginning of August.

**Comment by asmittle** [comment]
Great, thanks so much +1 for fantastic customer service!
