### ISSUE TITLE
Wordfence both 2FA and disable reCAPTCHA

### ISSUE THREAD

**Issue by imachequa** [hCaptcha/hcaptcha-wordpress-plugin#263]
It is not possible to authenticate when having 2FA active when using Wordfence.
Disabling hcaptcha when reCAPTCHA is present is not working on the page /wp-admin either or for that matter any page that is using reCAPTCHA when enable by means of Wordfence plugin.

It will be interesting to be able to work with 2FA solutions while being away from reCAPTCHA.

**Comment by kagg-design** [comment]
I have added compatibility with Wordfence Login Security and Wordfence Security. Tested with recaptcha on/off, 2FA on/off.

Will be published with v3.3.0 next week.

**Comment by imachequa** [comment]
Lovely!!!! it is working
