### ISSUE TITLE
This plugin conflicts with the official WordPress ActivityPub plugin

### ISSUE THREAD

**Issue by sindastra** [hCaptcha/hcaptcha-wordpress-plugin#265]
When enabling hCaptcha's "comment form" integration, comments coming in from the official WordPress ActivityPub plugin, are blocked.

**Comment by sindastra** [comment]
I reported it on the other side, too, see here: https://github.com/Automattic/wordpress-activitypub/issues/402

**Comment by e271828-** [comment]
@sindastra which versions of WP and this plugin did you try?

**Comment by sindastra** [comment]
At the time the issue was apparent:

- ActivityPub version 0.17.0 (still the latest version as of the time I'm writing this)
- hCaptcha version 2.9.0 (3.1.0 is the latest, untested)
- WordPress version 6.2.2 (6.3 is the latest)

I have disabled the hCpatcha "comment form" integration as a workaround, so that comments coming in from ActivityPub won't get lost. I am reporting this a bit late, but unless you have any reason to believe it's fixed now, it wouldn't be worth the risk of testing the latest version on a production site.

**Comment by kagg-design** [comment]
We do not support ActivityPub plugin so far, especially, considering that it is in the beta version.

I have added its support to our development plant. Integration should be done at the end of August.

**Comment by kagg-design** [comment]
I spent enough time and was unable to make ActivityPub work on my website. Site Health says that `Your WebFinger endpoint https://site.com/.well-known/webfinger?resource=acct:kagg@site.com does not return valid JSON for application/jrd+json`. Actually, it returns error `{"errors":{"activitypub_user_not_found":["User not found"]},"error_data":{"activitypub_user_not_found":{"status":404}}}`.

Let us wait until ActivityPub will be officially released. So far, I have no time to struggle with beta software, unfortunately.

**Comment by sindastra** [comment]
Just on the off-chance: Is that a real domain you ran this on? Because ActivityPub only works when it's actually online. On a live site, it should just work, even in Beta.

**Comment by kagg-design** [comment]
Yes, I tried it on my site https://kagg.eu.

**Comment by sindastra** [comment]
They released 1.0.0 today. They also added `\Activitypub\is_activitypub_request()` for third-party plugin developers, which might come in handy for this particular issue.
