### ISSUE TITLE
Compatibility with Passster Pro

### ISSUE THREAD

**Issue by salvia34** [hCaptcha/hcaptcha-wordpress-plugin#267]
Hello hCaptcha team,

I've encountered an issue where hCaptcha is not compatible with Passster Pro.

When I have both plugins activated, particularly when there are two instances of hCaptcha on a single page, for example with Ninja Forms and the other invoked by Passster, hCaptcha seems non-functional with a missing checkbox. 

This was discussed in the WordPress forum and it was advised to raise this issue here on GitHub. 

**Specifics:**

- **Issue**: The hCaptcha does not function correctly with a missing checkbox when there's another hCaptcha instance on the page, here invoked by the Passster plugin.
- **Passster Pro Reference**: [Passster WordPress Plugin Page](https://fr.wordpress.org/plugins/content-protector/)

Just for information: [Screenshot of hCaptcha settings from Passster Pro](https://i.ibb.co/64Px0BR/passster-hcaptcha.jpg)

In a related concern, I've observed that when I deactivate the Ninja Forms integration option in the hCaptcha settings, the field disappears, preventing me from further troubleshooting the issue. From a developer's standpoint, having the flexibility to manually insert the hCaptcha field, akin to the option with QuForm, would be extremely beneficial. This manual approach could be crucial in avoiding potential conflicts.

**Request**:
Ensure compatibility between hCaptcha and the Passster Pro plugin to allow both to function on the same page without conflicts.

Thank you for addressing this issue. I've reached out to the development team at Passster as well to ensure optimal compatibility between both plugins. Because ndividually, each plugin functions seamlessly, but together there seems to be a conflict.

Warm regards, 
Brigitte G.

**Comment by salvia34** [comment]
After some reflection, I'm wondering if this issue is solely related to an incompatibility with the Passster plugin, or is the bug triggered by ANY second instance of an hCaptcha on the same page? If you can confirm this, I will edit the title of this feature request.

**Comment by kagg-design** [comment]
Hello @salvia34,

Thank you for creating the feature request.

We are OK with several hCaptcha widgets on the same page - and you can have several forms with hCaptcha (let us say, Ninja forms - I have such a page on my test site).

Having another plugin (like Passster) that tries to run the hCaptcha API script is always a problem, as it uses another site key, and in any case - the hCaptcha API script is not designed to be launched several times on a page. To avoid the issue with the API script, our plugin blocks launching the script by the supported plugin (like Ninja Forms). An unsupported plugin (like Passter) launches the API script and creates a problem. That is why I need to add compatibility code to our plugin.

Next point - I see reCachtcha on your screenshot. Remember, reCaptcha and hCaptcha are not the same; they can conflict. And when Passster compatibility is done, you should deactivate reCaptcha in Passster.

**Comment by kagg-design** [comment]
Could you also send Passster Pro zip file to my email - info@kagg.eu. Thank you.

**Comment by kagg-design** [comment]
I have added compatibility with Passster free plugin from wp.org. The next version of the hCaptcha plugin hopefully will be released at the end of August.

**Comment by kagg-design** [comment]
Compatibility with Passster was added in v3.3.0.
