### ISSUE TITLE
UsersWP

### ISSUE THREAD

**Issue by dafogary** [hCaptcha/hcaptcha-wordpress-plugin#269]
Would it be possible to get integration with [UsersWP](https://userswp.io/)?

I can't seem to find a shortcode option in there forms.

**Comment by kagg-design** [comment]
We do not have this premium plugin. Can you send it for testing to my email info@kagg.eu? Thank you.

**Comment by kagg-design** [comment]
Compatibility added in v3.3.0. It should be released next week.
