### ISSUE TITLE
hCaptcha can be tricked by bots attempting brute force attacks

### ISSUE THREAD

**Issue by carlotafuro** [hCaptcha/hcaptcha-wordpress-plugin#270]
Look at the two examples of curl request that follow:

```
curl 'https://www.example.com/wp-login.php' \
-X POST  \
-H 'Referer: https://www.example.com/wp-login.php'  \
-H 'Content-Type: application/x-www-form-urlencoded'  \
--data-raw 'log=MYUSERNAME&pwd=MYPASSWORD' \
```

```
curl 'https://www.example.com/wp-login.php' \
-X POST  \
-H 'Referer: https://www.example.com/'  \
-H 'Content-Type: application/x-www-form-urlencoded'  \
--data-raw 'log=MYUSERNAME&pwd=MYPASSWORD' \
```

the first example is protected by hCaptcha and throws the hCaptcha error: "Please complete the hCaptcha"

the second example uses a different referer value and bypasses the hCaptcha check!

Consider removing the check on the referer in the verify() function:

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/master/src/php/WP/Login.php#L86

The verify() function check is already in wp_authenticate_user hook

**Comment by kagg-design** [comment]
It is more complex. The wp_authenticate_user hook is used by many plugins that we support, and we need to distinguish where the request comes from. That is why a check for referer was added.

But the problem exists, and I will think about what to do with it.

**Comment by kagg-design** [comment]
Thank you for the report. I have improved the login sequence in the v3.3.0 branch, which will be released soon.
