### ISSUE TITLE
Please add hCaptcha support for Blocksy, Blocksy Companion & Blocksy Companion Pro

### ISSUE THREAD

**Issue by Alok-S-Sharma** [hCaptcha/hcaptcha-wordpress-plugin#274]
Theme URL: https://wordpress.org/themes/blocksy/
Plugin URL: https://wordpress.org/plugins/blocksy-companion/
Website: https://creativethemes.com/blocksy/

**Comment by kagg-design** [comment]
Same question here - what to integrate? Does Blocksy have a Form?

**Comment by Alok-S-Sharma** [comment]
Please accept my sincere apologies, I am not sure what went wrong. Perhaps I may have become confused with some other theme or plugin.
