### ISSUE TITLE
Please add hCaptcha support for Stackable & Stackable Pro

### ISSUE THREAD

**Issue by Alok-S-Sharma** [hCaptcha/hcaptcha-wordpress-plugin#275]
Plugin URL: https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/
Website: https://wpstackable.com/

**Comment by kagg-design** [comment]
I do not see a Form block there. Does Stackable have it?

**Comment by Alok-S-Sharma** [comment]
Please accept my sincere apologies, I am not sure what went wrong. Perhaps I may have become confused with some other theme or plugin.
