### ISSUE TITLE
HCaptcha does not block Brevo/SendinBlue forms submissions

### ISSUE THREAD

**Issue by ACCK-fabien** [hCaptcha/hcaptcha-wordpress-plugin#277]
In my Website, (https://www.tcap-tpro.fr/, in the footer of evey page), the Brevo form can be sent even if the HCaptcha IFrame was not touched.
The IFrame was added automaticaly using the HCaptcha plugin's Integrations page, as I do with Contact Form 7 forms.

**Comment by e271828-** [comment]
@ACCK-fabien does this still happen with the latest version?

**Comment by ACCK-fabien** [comment]
@e271828- Yes, the HCaptcha for Worpress plugin is up to date (3.3.2) and so is the Brevo plugin (3.1.71 since this morning).
I don't know if the sendinblue plugin changed a lot with the name change to Brevo since I did not use a Brevo form before.
 
Here is the system info : 
### Begin System Info ###


-- hCaptcha Info --

Version:                              3.3.2
Site key:                             Set
Secret key:                           Set
Theme:                                light
Size:                                 normal
Language:                             
Mode:                                 live
Custom Themes:                        Off
Config Params:                        Not set
Turn Off When Logged In:              Off
Disable reCAPTCHA Compatibility:      Off
Whitelisted IPs:                      Not set
Login attempts before hCaptcha:       0
Failed login attempts interval, min:  15
Delay showing hCaptcha, ms:           -100

--- Active plugins and themes ---

Contact Form 7:                       
  Form:                               On
Divi:                                 
  Divi Comment Form:                  Off
  Divi Contact Form:                  Off
  Divi Email Optin Form:              Off
  Divi Login Form:                    Off
Sendinblue:                           
  Form:                               On
WP Core:                              
  Comment Form:                       Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Post/Page Password Form:            Off
  Register Form:                      Off

--- Inactive plugins and themes ---

ACF Extended:                         
  ACF Extended Form:                  Off
Asgaros:                              
  Form:                               Off
Avada:                                
  Avada Form:                         Off
Back In Stock Notifier:               
  Back In Stock Notifier Form:        Off
bbPress:                              
  New Topic Form:                     Off
  Reply Form:                         Off
Beaver Builder:                       
  Contact Form:                       Off
  Login Form:                         Off
Brizy:                                
  Form:                               Off
BuddyPress:                           
  Create Group Form:                  Off
  Registration Form:                  Off
Classified Listing:                   
  Contact Form:                       Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Colorlib Login Customizer:            
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Download Manager:                     
  Button:                             Off
Easy Digital Downloads:               
  Checkout Form:                      Off
Elementor Pro:                        
  Form:                               Off
Fluent Forms:                         
  Form:                               Off
Formidable Forms:                     
  Form:                               Off
Forminator:                           
  Form:                               Off
GiveWP:                               
  Form:                               Off
Gravity Forms:                        
  Form:                               Off
Jetpack:                              
  Contact Form:                       Off
Kadence:                              
  Kadence Form:                       Off
  Kadence Advanced Form:              Off
Mailchimp for WP:                     
  Form:                               Off
MemberPress:                          
  Login Form:                         Off
  Registration Form:                  Off
Ninja Forms:                          
  Form:                               Off
Otter Blocks:                         
  Form:                               Off
Paid Memberships Pro:                 
  Checkout Form:                      Off
  Login Form:                         Off
Passster:                             
  Protection Form:                    Off
Profile Builder:                      
  Login Form:                         Off
  Recover Password Form:              Off
  Register Form:                      Off
Quform:                               
  Form:                               Off
Subscriber:                           
  Form:                               Off
Support Candy:                        
  Form:                               Off
Theme My Login:                       
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Ultimate Member:                      
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Users WP:                             
  Forgot Password Form:               Off
  Login Form:                         Off
  Register Form:                      Off
WooCommerce:                          
  Checkout Form:                      Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Order Tracking Form:                Off
  Registration Form:                  Off
WooCommerce Wishlists:                
  Create List Form:                   Off
Wordfence:                            
  Login Form:                         Off
WPDiscuz:                             
  Comment Form:                       Off
  Subscribe Form:                     Off
WPForms:                              
  Lite:                               Off
  Pro:                                Off
WPForo:                               
  New Topic Form:                     Off
  Reply Form:                         Off

-- Site Info --

Site URL:                             https://www.tcap-tpro.fr
Home URL:                             https://www.tcap-tpro.fr
Multisite:                            No

-- WordPress Configuration --

Version:                              6.3.1
Language:                             fr_FR
User Language:                        fr_FR
Permalink Structure:                  /%postname%/
Active Theme:                         Divi 4.22.1
Show On Front:                        page
Page On Front:                        Accueil (#7)
Page For Posts:                       Unset
ABSPATH:                              /homepages/22/d4297524217/htdocs/wordpress/
Table Prefix:                         Length: 5   Status: Acceptable
WP_DEBUG:                             Disabled
Memory Limit:                         40M
Registered Post Stati:                publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, dp-rewrite-republish
Revisions:                            Enabled

-- WordPress Uploads/Constants --

WP_CONTENT_DIR:                       /homepages/22/d4297524217/htdocs/wordpress/wp-content
WP_CONTENT_URL:                       https://www.tcap-tpro.fr/wp-content
UPLOADS:                              Not set
wp_uploads_dir() path:                /homepages/22/d4297524217/htdocs/wordpress/wp-content/uploads/2023/10
wp_uploads_dir() url:                 https://www.tcap-tpro.fr/wp-content/uploads/2023/10
wp_uploads_dir() basedir:             /homepages/22/d4297524217/htdocs/wordpress/wp-content/uploads
wp_uploads_dir() baseurl:             https://www.tcap-tpro.fr/wp-content/uploads

-- Must-Use Plugins --

IONOS Marketplace:                    1.1.5
WordPress automation by Installatron: 

-- WordPress Active Plugins --

Broken Link Checker:                                            2.2.2
Complianz | GDPR/CCPA Cookie Consent:                           6.5.4
Contact Form 7:                                                 5.8.1
Contact Form CFDB7:                                             1.2.6.7
Disable auto-update Email Notifications:                        1.4.0
Divi Contact Form 7:                                            1.3.4
hCaptcha for WordPress:                                         3.3.2
IONOS Assistant:                                                8.5.4
IONOS Help:                                                     2.2.1
IONOS Journey:                                                  2.0.0
IONOS Login:                                                    2.2.1
IONOS Navigation:                                               1.0.7
IONOS Performance:                                              2.0.3
IONOS Security:                                                 1.1.0
Leaflet Map:                                                    3.3.1
MailPoet:                                                       4.30.0
Newsletter, SMTP, Email marketing and Subscribe forms by Brevo: 3.1.71
OSM:                                                            6.0.1
Really Simple SSL:                                              7.1.1
WP-Optimize - Clean, Compress, Cache:                           3.2.19
Yoast Duplicate Post:                                           4.5
Yoast SEO:                                                      21.3

-- WordPress Inactive Plugins --

All-in-One WP Migration:                                        7.78
Better Search Replace:                                          1.4.3

-- Webserver Configuration --

PHP Version:                          8.0.30
MySQL Version:                        10.6.15
Webserver Info:                       Apache

-- PHP Configuration --

Memory Limit:                         -1
Upload Max Size:                      64M
Post Max Size:                        64M
Upload Max Filesize:                  64M
Time Limit:                           50000
Max Input Vars:                       5000
Display Errors:                       N/A

-- PHP Extensions --

cURL:                                 Supported
fsockopen:                            Supported
SOAP Client:                          Installed
Suhosin:                              Not Installed

-- Session Configuration --

Session:                              Disabled

### End System Info ###

**Comment by kagg-design** [comment]
Thank you for providing extensive information about the issue. The problem was with the SendInBlue placed in the footer. It took substantial time to get it. Due to the absence of hooks in SendInBlue, the related hCaptcha functionality was done via auto-verify forms, which can only work in the post content.

I have added registration for the SendInBlue form for auto-verification in any place. The 3.3.3 version with the fix will be released next week.
