### ISSUE TITLE
LearnDash compatibiity

### ISSUE THREAD

**Issue by kagg-design** [hCaptcha/hcaptcha-wordpress-plugin#280]
A compatibility issue with LearnDash was reported on wp.org: https://wordpress.org/support/topic/the-captcha-is-not-being-displayed/#post-17062095

We do not have LearnDash, so could you provide it to my email info@kagg.eu?

Thank you.

**Comment by qRodp** [comment]
Hey, I've sent it to your email

**Comment by kagg-design** [comment]
Well received, thanks!

**Comment by kagg-design** [comment]
Thank you for sharing premium plugins for testing.

I have tested intensively LoginPress, LoginPressPro, LoginPress Pro + HideLogin and did not find any issues with the login form.

However, when I installed LearnDash, I encountered an issue with login via its customized login form.

I have added integration with the LearnDash Login form, which does not break previously added integrations with plugins and themes customizing the standard WP login form. The combination of LearnDash, LoginPress Pro and HideLogin plugins was also tested and worked well.

The next version, 3.3.3 of the hCaptcha plugin, will be released next week.

**Comment by qRodp** [comment]
Hi Igor,

Thanks, I have just tried v3.3.3 and it doesn’t work. I don’t know why. I have tried activating hcaptcha on wordpress, learn dash but I can’t see any captcha. Any ideas ?

I have tried activating wpdiscuz and it has worked.

**Comment by kagg-design** [comment]
Hi Rod,

Could you explain how namely it does not work? Could you share the link to the problem page?

**Comment by qRodp** [comment]
Currently, I have deactivated hcaptcha and removes false users manually ^^

But the issue was same as lately. Hcaptcha doesn’t appear on signup page (loginpress one or learndash one, even after new update). So if I try to create a new member, it returns error that hcaptcha is incorrect but it can’t be validated because it doesn’t appear on the page :)
