### ISSUE TITLE
Hcaptcha not loading correctly under brevo forms

### ISSUE THREAD

**Issue by LS-DDrop** [hCaptcha/hcaptcha-wordpress-plugin#281]
In our website (https://sitomonopagina.it/pagamento/order-received/) we can't see the hcaptcha iframe at all, despite using the latest integration (3.3.2) and brevo plugin (3.1.70)

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/126774166/dd768d32-b867-4a8a-ad01-0424c4dc7b31)

the same is true for the homepage, where the subscription form redirects to one of the other instances of hcaptcha around the page, on a cf7 form (it still doesn't subscribe if that instance is filled correctly).

**Comment by kagg-design** [comment]
How did you insert the form into the page? It should be inserted via [sibwp_form id=x] shortcode.

**Comment by LS-DDrop** [comment]
It is indeed loaded that way, both on the home and the other page.

**Comment by kagg-design** [comment]
The problem on the order-received page is related to the fact that you have changed `<input type="submit"` to the `<button ... type="submit">` in Brevo form. I have added recognition of such form to v3.3.3, which will be released next week.

**Comment by kagg-design** [comment]
What concerns the second part of your problem - scrolling to the wrong form when there is an error - is a bug in the Brevo plugin, in the file `/wp-content/plugins/mailin/js/mailin-front.js`. "I cannot fix it.

You can reach the Brevo team to fix this issue when 2+ forms are on the page, and the Brevo form is not the first one.

**Comment by LS-DDrop** [comment]
I just updated to 3.3.3 and it now blocks the checkout process (and triggers a critical error in this page https://sitomonopagina.it/pagamento/order-received/ )
we are reverting back to 3.3.2 for right now.
