### ISSUE TITLE
hcaptcha plugin v3.3.3 doesn't work on WP multisite anymore.

### ISSUE THREAD

**Issue by dizzyza** [hCaptcha/hcaptcha-wordpress-plugin#287]
After getting the latest update 3.3.3 the plugin no longer works as expected on wordpress multisite.

I've tested with hcaptcha support via the .HAR file and they confirmed there is no request to hcaptcha on the wp-login.php
Testing with a normal WP site on the same server the plugin works as expected.

### Begin System Info ###

-- hCaptcha Info --

Version:                              3.3.3
Site key:                             Set
Secret key:                           Set
Theme:                                light
Size:                                 compact
Language:                             Auto-detect
Mode:                                 live
Custom Themes:                        Off
Config Params:                        Not set
Turn Off When Logged In:              Off
Disable reCAPTCHA Compatibility:      Off
Whitelisted IPs:                      Set
Login attempts before hCaptcha:       
Failed login attempts interval, min:  1
Delay showing hCaptcha, ms:           -100

--- Active plugins and themes ---

Elementor Pro:                        
  Form:                               Off
Gravity Forms:                        
  Form:                               Off
Wordfence:                            
  Login Form:                         Off
WP Core:                              
  Comment Form:                       On
  Login Form:                         On
  Lost Password Form:                 On
  Post/Page Password Form:            Off
  Register Form:                      On

--- Inactive plugins and themes ---

ACF Extended:                         
  ACF Extended Form:                  Off
Asgaros:                              
  Form:                               Off
Avada:                                
  Avada Form:                         Off
Back In Stock Notifier:               
  Back In Stock Notifier Form:        Off
bbPress:                              
  New Topic Form:                     On
  Reply Form:                         On
Beaver Builder:                       
  Contact Form:                       Off
  Login Form:                         Off
Brizy:                                
  Form:                               Off
BuddyPress:                           
  Create Group Form:                  On
  Registration Form:                  On
Classified Listing:                   
  Contact Form:                       Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Colorlib Login Customizer:            
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Contact Form 7:                       
  Form:                               On
Divi:                                 
  Divi Comment Form:                  Off
  Divi Contact Form:                  Off
  Divi Email Optin Form:              Off
  Divi Login Form:                    Off
Download Manager:                     
  Button:                             Off
Easy Digital Downloads:               
  Checkout Form:                      Off
Fluent Forms:                         
  Form:                               Off
Formidable Forms:                     
  Form:                               Off
Forminator:                           
  Form:                               Off
GiveWP:                               
  Form:                               Off
Jetpack:                              
  Contact Form:                       On
Kadence:                              
  Kadence Form:                       Off
  Kadence Advanced Form:              Off
LearnDash LMS:                        
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Mailchimp for WP:                     
  Form:                               On
MemberPress:                          
  Login Form:                         Off
  Registration Form:                  Off
Ninja Forms:                          
  Form:                               On
Otter Blocks:                         
  Form:                               Off
Paid Memberships Pro:                 
  Checkout Form:                      Off
  Login Form:                         Off
Passster:                             
  Protection Form:                    Off
Profile Builder:                      
  Login Form:                         Off
  Recover Password Form:              Off
  Register Form:                      Off
Quform:                               
  Form:                               Off
Sendinblue:                           
  Form:                               Off
Subscriber:                           
  Form:                               On
Support Candy:                        
  Form:                               Off
Theme My Login:                       
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Ultimate Member:                      
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Users WP:                             
  Forgot Password Form:               Off
  Login Form:                         Off
  Register Form:                      Off
WooCommerce:                          
  Checkout Form:                      On
  Login Form:                         On
  Lost Password Form:                 On
  Order Tracking Form:                Off
  Registration Form:                  On
WooCommerce Wishlists:                
  Create List Form:                   On
WPDiscuz:                             
  Comment Form:                       Off
  Subscribe Form:                     Off
WPForms:                              
  Lite:                               On
  Pro:                                Off
WPForo:                               
  New Topic Form:                     On
  Reply Form:                         On

-- Site Info --

Site URL:                             
Home URL:                             
Multisite:                            Yes

-- WordPress Configuration --

Version:                              6.3.2
Language:                             en_US
User Language:                        en_US
Permalink Structure:                  /%postname%/
Active Theme:                         Neo 0.1
Show On Front:                        page
Page On Front:                        Sample Page (#2)
Page For Posts:                       Unset
ABSPATH:                              //
Table Prefix:                         Length: 3   Status: Acceptable
WP_DEBUG:                             Disabled
Memory Limit:                         2048M
Registered Post Stati:                publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed
Revisions:                            Enabled

-- WordPress Uploads/Constants --

WP_CONTENT_DIR:                       //wp-content
WP_CONTENT_URL:                       /wp-content
UPLOADS:                              Not set
wp_uploads_dir() path:                //wp-content/uploads/2023/10
wp_uploads_dir() url:                 /wp-content/uploads/2023/10
wp_uploads_dir() basedir:             //wp-content/uploads
wp_uploads_dir() baseurl:             /wp-content/uploads

-- Must-Use Plugins --

Disable Auto Update Mails:            1.0
Project Staging Utilities Plugin:     1.0

-- WordPress Active Plugins --

Elementor:                                                3.16.4 (needs update - 3.16.6)
Elementor Pro:                                            3.16.2
Essential Addons for Elementor:                           5.8.11
Essential Addons for Elementor - Pro:                     5.7.0
GP Premium:                                               2.3.2
Gravity Forms:                                            2.7.15
Simple 301 Redirects:                                     2.0.9
Simple CSS:                                               1.1.1
Yoast SEO:                                                21.4

-- WordPress Inactive Plugins --

Akismet Anti-spam: Spam Protection:                       5.3
Autoptimize:                                              3.1.9
Beehive Pro:                                              3.4.9
CookieYes | GDPR Cookie Consent:                          3.1.5
Custom Product Tabs for WooCommerce:                      1.8.5
Domain Mapping:                                           4.4.3.3
Elementor Scheme_Color and Scheme_Typography Class Issue: 1
ERE Colors - Essential Real Estate Add-On:                1.5
Essential Real Estate:                                    4.2.9
Extras for Elementor:                                     2.2.51
G-Forms hCaptcha:                                         1.3.1
GTM4WP:                                                   1.18.1
hCaptcha for WordPress:                                   3.3.3
Hummingbird Pro:                                          3.6.0
JetMenu:                                                  2.0.9
Lightweight Grid Columns:                                 1.0
Login IP & Country Restriction:                           6.4.1
Login LockDown:                                           v1.8.1
MDS Collivery:                                            3.1.28
Mobile Redirect:                                          1.7.2
New Blog Templates:                                       2.8.7-beta-1
New Blog Templates:                                       2.8.6
NMP Admin Limiter:                                        1.1.1
Page Builder by SiteOrigin:                               2.26.1
PopBox For Elementor:                                     1.0.7
PowerPack Pro for Elementor:                              2.7.10
Rank Math SEO:                                            1.0.202 (needs update - 1.0.204)
Really Simple SSL:                                        7.1.3
SiteOrigin Widgets Bundle:                                1.55.1
Smart Slider 3 Pro:                                       3.5.0.11
Templately:                                               2.2.5 (needs update - 2.2.6)
User Role Editor:                                         4.64
W3 Total Cache:                                           2.5.0
Widgetkit:                                                2.9.8
WooCommerce:                                              8.2.1
WooCommerce Payfast Gateway:                              1.5.9
Wordfence Security:                                       7.10.4
WordPress Importer:                                       0.8.1
WP Mail SMTP:                                             3.9.0
WPMU DEV Dashboard:                                       4.11.22
YITH Request a Quote for WooCommerce:                     2.26.0
Yoast Test Helper:                                        1.17

-- Network Active Plugins --

CookieYes | GDPR Cookie Consent: 3.1.5Domain Mapping: 4.4.3.3G-Forms hCaptcha: 1.3.1GP Premium: 2.3.2hCaptcha for WordPress: 3.3.3Login IP &amp; Country Restriction: 6.4.1NMP Admin Limiter: 1.1.1Really Simple SSL: 7.1.3Mobile Redirect: 1.7.2User Role Editor: 4.64Wordfence Security: 7.10.4WPMU DEV Dashboard: 4.11.22
-- Webserver Configuration --

PHP Version:                          8.2.10
MySQL Version:                        10.3.28
Webserver Info:                       nginx/1.14.1

-- PHP Configuration --

Memory Limit:                         2048M
Upload Max Size:                      64M
Post Max Size:                        64M
Upload Max Filesize:                  64M
Time Limit:                           300
Max Input Vars:                       1000
Display Errors:                       N/A

-- PHP Extensions --

cURL:                                 Supported
fsockopen:                            Supported
SOAP Client:                          Installed
Suhosin:                              Not Installed

-- Session Configuration --

Session:                              Disabled

**Comment by kagg-design** [comment]
Thank you for providing the SystemInfo. I see that you have G-Forms hCaptcha, which definitely conflicts with our plugin. It should be deactivated.

Also, we should focus on the problem by deactivating plugins one by one and changing the theme to a standard one. This will bring an understanding of the conflict (if it is the reason).

I am wondering why paths are written like //. Did you edit the SystemInfo?

I tried to reproduce the issue on a local multisite. The login form works properly. Could you provide a link to the problem page?

**Comment by dizzyza** [comment]
Thanks for the response! I have tested deactivating G-Forms hCaptcha and it made no difference. 
As for the paths. We are running this site in chroot and it is a result of this process. 
This is a production environment but will test deactivating all plugins and switching to standard theme. Will revert once tested!

**Comment by dizzyza** [comment]
After testing further. Changing to the default theme seems to have sorted the issue!
