### ISSUE TITLE
Cannot save settings - Save Button not active when adding keys on Wordpress site 

### ISSUE THREAD

**Issue by statenational** [hCaptcha/hcaptcha-wordpress-plugin#288]
I am trying to set up the Free version of hCaptcha one of my sites at: https://tasa.americanstatenationals.org/
 
We were using the Google Captcha but it was having failure issues and not allowing clients to pass through it.
 
When I open the hCaptcha page in wordpress there is an active Save Button at the bottom. The moment I add my sitekey and/or secretkey the Save Button disappears so I cannot save my settings. 
 
I checked for plugin conflicts by deactivating everything but the hCaptcha plugin but that did not help.
 
Attached is a copy of the system settings.
 
Can you help me with this?
 
Best Regards,
 
by: Tony Mendoza Jr. © - All Rights Reserved
American State National - Web Administrator
Nevada City, California
6IVP21223
US-CA-251358351
[settings.txt](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/files/13079089/settings.txt)

**Comment by kagg-design** [comment]
The Save button does not disappear but becomes inactive. At the same time, a message appears on the top: "Credentials changed. Please complete hCaptcha and check the site config.". You should complete the hCaptcha by clicking on it under the label "Active hCaptcha to Check Site Config". It is live hCaptcha! After passing the challenge, you will know if your credentials are correctly entered.

This protects the user from self-locking from the login upon entering the wrong credentials.

**Comment by statenational** [comment]
Thank you kagg-design! Your response helped me figure it out. I was testing the captcha successfully but I was not hitting the Site Config button after doing that. I am glad it was a simple "operator error"

Best Regards,
Tony
