### ISSUE TITLE
Contact Form 7 - don't add _wpnonce for guests

### ISSUE THREAD

**Issue by rinart73** [hCaptcha/hcaptcha-wordpress-plugin#292]
Contact Form 7 plugin adds `_wpnonce` hidden field **only for logged in users** but not for guests because:

- Nonces are primarily designed for to be used for logged in users;
- Pages are often cached for guests, which means that after 12 hours (standard nonce expiration), a form with nonce would stop working.

I’ve noticed that if I activate Contact Form 7 integration, `_wpnonce` hidden field is being added **regardless of logged in status**. Because of this forms stop working on cached pages after a while.

“_Just don’t cache pages with contact form_” isn’t really a solution, because there are websites that have contact form on every page (in footer, for example).

Here is where nonce field is added in hCaptcha: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/66b4a1e68874e62a64c666a3a76010e831d42b8d/src/php/CF7/CF7.php#L166

Here is how Contact Form 7 handles it: https://github.com/rocklobster-in/contact-form-7/blob/2f66b3b9002ab16c9a2a5e19a26440dc710bec57/includes/contact-form.php#L713

**Comment by kagg-design** [comment]
Nonce protects from CSRF even for users who are not logged in. CF7 author can proceed in his way; it is his plugin.

[Here is a good article](https://docs.wp-rocket.me/article/975-nonces-and-cache-lifespan) from the lead caching plugin for WordPress explaining how to cache pages containing nonce.

And finally, we [verify nonce](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/master/src/php/includes/request.php#L227) for logged-in users only.

**Comment by kagg-design** [comment]
With LiteSpeed Cache, when you can purge cache once a day only, you can increase nonce tick.

[Nonce life documentation](https://developer.wordpress.org/reference/hooks/nonce_life/).

Set the lifetime to more than 2 days. The default lifespan is 1 day, split equally by 2 ticks. The cache time must be less than 1 tick.

**Comment by rinart73** [comment]
This is how WordPress nonce tick is calculated: [`ceil( time() / ( $nonce_life / 2 ) )`.](https://github.com/WordPress/WordPress/blob/078ed1a3a64207d20ab07822cd93833eb2f8986c/wp-includes/pluggable.php#L2283)
So suppose we set `wp_rest` nonce life for guests to 4 days and set cache to auto-purge every day at 00:01, because the nonce tick changes every other day at 00:00. If we set life to 2 days, it will change every day at 00:00.

Assuming that we're using a VPS (so shared hosting users are in trouble) that allows us to run Linux cron to call WordPress cron every 5-10 minutes, we'll have 5-10 minutes (00:00-00:10) of contact form not working. Which is maybe not that big of a deal, but still, not exactly ideal.

Could you perhaps add an `apply_filter` that would allow to change the output of hCaptcha? Because I'm not very thrilled with the nonce solution to be honest.

**Comment by kagg-design** [comment]
How WP ticks work and why WP use two ticks need to be clarified. No 5-10-minute interruption will happen because the second tick accepts nonces from the first tick. You can find it in the WP nonce code. And this is the principal moment why WP creates two ticks.

You should follow the advice of the WP Rocket creator: "Set cache lifespan to 10 hours or less". In your case, it means: "Set the nonce lifetime two times longer than the cache lifespan", i.e., "Set the nonce lifetime 48 hours+".
