### ISSUE TITLE
hCaptcha blocking Stripe Express Checkouts using ApplePay or Google Pay

### ISSUE THREAD

**Issue by winklebleck** [hCaptcha/hcaptcha-wordpress-plugin#296]
The hCaptch plugin is breaking Stripe Express checkout from the product page and cart page. Getting a "Please complete the hCaptcha" alert even though the Captcha is not on those pages.

Using the WooCommerce Stripe Gateway plugin
The hCaptcha integrations are only WooCommerce Checkout Form

![hCaptcha-error](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/3142464/e72e4197-0715-46dc-8c4f-a535c9779af7)

**Comment by kagg-design** [comment]
I have installed the plugin and created a Stripe account (which is painful). And I was unable to see the issue.

Could you share the link to the page when you have a problem? Thank you.

**Comment by kagg-design** [comment]
Please let me know today when you are ready. You can drop a line to info@kagg.eu. Thanks.

**Comment by kagg-design** [comment]
Closed as non-reproducible.
