### ISSUE TITLE
Hcapatcha's integration with Mailpoet outputs "Bad hCaptcha nonce!" errors

### ISSUE THREAD

**Issue by ACCK-fabien** [hCaptcha/hcaptcha-wordpress-plugin#297]
Hello,

I have a problem with Hcapatcha's integration with Mailpoet.
When I activate the integration for Mailpoet, everytime Hcaptcha seems to be used, there is a "Bad hCaptcha nonce!" error :
- When there is a form, there is no hcaptcha iframe and the form is locked
- When I want to access the Mailpoet forms in the back office the form is hidden and there is an error message
![bug_mailpoet_1](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/142806224/d53114c6-52ef-420f-a3b0-443fd4a7468b)
- When I want to access the list of my subscribers I can't see any. In this case, there is one error message that seams to appear for each time a refresh is done, so 2 messages every second, which results in lots of errors on the page
![bug_mailpoet_2](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/142806224/ef191b2c-3542-4879-8e19-0b696d8fa37a)

These errors were visible in another website I also work on so maybe it's a problem on Mailpoet's side ? I could contact them if needed.
In the meantime, I deactivated hcaptcha on the website.

Thank you in advance,
Fabien.

Just in case, here is the site's system info : 
### Begin System Info ###

-- hCaptcha Info --

Version:                              3.4.1
Site key:                             Set
Secret key:                           Set
Theme:                                light
Size:                                 normal
Language:                             Auto-detect
Mode:                                 live
Custom Themes:                        Off
Config Params:                        Not set
Turn Off When Logged In:              Off
Disable reCAPTCHA Compatibility:      Off
Whitelisted IPs:                      Not set
Login attempts before hCaptcha:       0
Failed login attempts interval, min:  15
Delay showing hCaptcha, ms:           -100

--- Active plugins and themes ---

Contact Form 7:                       
  Form:                               On
Divi:                                 
  Divi Comment Form:                  Off
  Divi Contact Form:                  Off
  Divi Email Optin Form:              Off
  Divi Login Form:                    Off
MailPoet:                             
  Form:                               On
WP Core:                              
  Comment Form:                       Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Post/Page Password Form:            Off
  Register Form:                      Off

--- Inactive plugins and themes ---

ACF Extended:                         
  ACF Extended Form:                  Off
Asgaros:                              
  Form:                               Off
Avada:                                
  Avada Form:                         Off
Back In Stock Notifier:               
  Back In Stock Notifier Form:        Off
bbPress:                              
  New Topic Form:                     Off
  Reply Form:                         Off
Beaver Builder:                       
  Contact Form:                       Off
  Login Form:                         Off
Brizy:                                
  Form:                               Off
BuddyPress:                           
  Create Group Form:                  Off
  Register Form:                      Off
Classified Listing:                   
  Contact Form:                       Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Colorlib Login Customizer:            
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Download Manager:                     
  Button:                             Off
Easy Digital Downloads:               
  Checkout Form:                      Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Elementor Pro:                        
  Form:                               Off
Fluent Forms:                         
  Form:                               Off
Formidable Forms:                     
  Form:                               Off
Forminator:                           
  Form:                               Off
GiveWP:                               
  Form:                               Off
Gravity Forms:                        
  Form:                               Off
Jetpack:                              
  Contact Form:                       Off
Kadence:                              
  Kadence Form:                       Off
  Kadence Advanced Form:              Off
LearnDash LMS:                        
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Mailchimp for WP:                     
  Form:                               Off
MemberPress:                          
  Login Form:                         Off
  Register Form:                      Off
Ninja Forms:                          
  Form:                               Off
Otter Blocks:                         
  Form:                               Off
Paid Memberships Pro:                 
  Checkout Form:                      Off
  Login Form:                         Off
Passster:                             
  Protection Form:                    Off
Profile Builder:                      
  Login Form:                         Off
  Recover Password Form:              Off
  Register Form:                      Off
Quform:                               
  Form:                               Off
Sendinblue:                           
  Form:                               Off
Simple Basic Contact Form:            
  Form:                               Off
Simple Download Monitor:              
  Form:                               Off
Subscriber:                           
  Form:                               Off
Support Candy:                        
  Form:                               Off
Theme My Login:                       
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Ultimate Member:                      
  Login Form:                         Off
  Lost Password Form:                 Off
  Register Form:                      Off
Users WP:                             
  Forgot Password Form:               Off
  Login Form:                         Off
  Register Form:                      Off
WooCommerce:                          
  Checkout Form:                      Off
  Login Form:                         Off
  Lost Password Form:                 Off
  Order Tracking Form:                Off
  Register Form:                      Off
WooCommerce Wishlists:                
  Create List Form:                   Off
Wordfence:                            
  Login Form:                         Off
WP Job Openings:                      
  Form:                               Off
WPDiscuz:                             
  Comment Form:                       Off
  Subscribe Form:                     Off
WPForms:                              
  Lite:                               Off
  Pro:                                Off
WPForo:                               
  New Topic Form:                     Off
  Reply Form:                         Off

-- Site Info --

Site URL:                             https://www.bxcelestinmichel.org
Home URL:                             https://www.bxcelestinmichel.org
Multisite:                            No

-- WordPress Configuration --

Version:                              6.4.1
Language:                             fr_FR
User Language:                        fr_FR
Permalink Structure:                  /%postname%/
Active Theme:                         Divi 4.23.1
Show On Front:                        page
Page On Front:                        Accueil (#9)
Page For Posts:                       Unset
ABSPATH:                              /home/acckfru/bxcelestinmichel/
Table Prefix:                         Length: 7   Status: Acceptable
WP_DEBUG:                             Disabled
Memory Limit:                         40M
Registered Post Stati:                publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, acf-disabled
Revisions:                            Enabled

-- WordPress Uploads/Constants --

WP_CONTENT_DIR:                       /home/acckfru/bxcelestinmichel/wp-content
WP_CONTENT_URL:                       https://www.bxcelestinmichel.org/wp-content
UPLOADS:                              Not set
wp_uploads_dir() path:                /home/acckfru/bxcelestinmichel/wp-content/uploads/2023/11
wp_uploads_dir() url:                 https://www.bxcelestinmichel.org/wp-content/uploads/2023/11
wp_uploads_dir() basedir:             /home/acckfru/bxcelestinmichel/wp-content/uploads
wp_uploads_dir() baseurl:             https://www.bxcelestinmichel.org/wp-content/uploads

-- WordPress Active Plugins --

ACCK Toolkit:                                         2.0
Advanced Custom Fields:                               6.2.4
Contact Form 7:                                       5.8.3
Contact Form CFDB7:                                   1.2.6.7
Divi Forms Styler:                                    2.0.2
hCaptcha for WordPress:                               3.4.1
Leaflet Map:                                          3.3.1
MailPoet:                                             4.38.0
Matomo Analytics - Ethical Stats. Powerful Insights.: 4.15.3
PDF Embedder:                                         4.6.4
Really Simple SSL:                                    7.2.0
Yoast SEO:                                            21.6

-- WordPress Inactive Plugins --

Akismet Anti-spam: Spam Protection:                   5.3

-- Webserver Configuration --

PHP Version:                          8.0.30
MySQL Version:                        8.0.34
Webserver Info:                       Apache

-- PHP Configuration --

Memory Limit:                         512M
Upload Max Size:                      128M
Post Max Size:                        130M
Upload Max Filesize:                  128M
Time Limit:                           165
Max Input Vars:                       16000
Display Errors:                       N/A

-- PHP Extensions --

cURL:                                 Supported
fsockopen:                            Supported
SOAP Client:                          Installed
Suhosin:                              Not Installed

-- Session Configuration --

Session:                              Disabled

**Comment by kagg-design** [comment]
Hello Fabien,

Thank you for the report.

You have JS errors on the front end. Therefore, the hCaptcha cannot be initialized. To make it work, you need to fix the following bugs on the front end.

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/60dce2f4-b843-4a31-82db-ca53b4220be9)

**Comment by kagg-design** [comment]
Issues reported in admin are valid; apologies. Fixed in v3.5.0, to be released next week.

**Comment by ACCK-fabien** [comment]
Thanks ! Have a great day !
