### ISSUE TITLE
Please add support for Elementor forms

### ISSUE THREAD

**Issue by numanzahid** [hCaptcha/hcaptcha-wordpress-plugin#30]
Hi developers,

Please add hcaptcha support for Elementor forms.

**Comment by e271828-** [comment]
Hi, please ask Elementor to add native support. This plugin is just a temporary solution until other plugins integrate hCaptcha natively.

**Comment by MrCater** [comment]
Yes please

**Comment by yeswycan** [comment]
Yes, must have ! Please :D

**Comment by kagg-design** [comment]
Added in v1.1.30, will be released at the end of September.
