### ISSUE TITLE
Version 3.5.0

### ISSUE THREAD

**Issue by toolgirl** [hCaptcha/hcaptcha-wordpress-plugin#301]
Not working in WP sites. hCaptcha shows as an empty box with the icon in Ninja Forms. This is true if there is a file upload add on and if there isn't. 
Examples:
https://www.3plr.com/contact-us/

**Comment by kagg-design** [comment]
Everything works well. You need to move the mouse or scroll to start the script, which renders hCaptcha.

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/8730addc-0cea-487c-bff4-0e23b9ad75a7)

I successfully submitted the form:
![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/f1f3586d-be9e-4a6c-bf59-638684931e93)

To prevent delayed hCaptcha rendering, you may set 0 to "Delay showing hCaptcha, ms" on hCaptcha General settings page.
