### ISSUE TITLE
Bypassing for automated testing

### ISSUE THREAD

**Issue by asafm7** [hCaptcha/hcaptcha-wordpress-plugin#303]
I'm using Testim.io for automated UI and functional testing.

I'm looking for ways to let the test bypass hCaptcha.

You have IP whitelisting, but it doesn't seem Testim.io provides permanent IPs.

Other methods can be bypassing according to a query param, a user agent, or a cookie.

A general "maybe_bypass" filter can enable developers to implement these methods per their needs.

Searching through the code, I couldn't find a similar filter, but maybe I missed something.

Let me know what might be the best option.

**Comment by kagg-design** [comment]
You can use the `hcap_activate` filter. It is described in the readme.txt.

**Comment by asafm7** [comment]
Thank you @kagg-design .

I tried and it didn't work.

I even tried `add_filter('hcap_activate', '__return_false', 100);` and it has no effect.

I'm using the Comments and Jetpack Contact Form integrations

**Comment by asafm7** [comment]
The code does work when placed in a mu-plugin

**Comment by kagg-design** [comment]
I don't know where you add the filter and how your tests are organized. The filter works, as you can see.

**Comment by asafm7** [comment]
Thank you @kagg-design .

The readme file you referred to states the filter should be placed in the "theme's `functions.php` file".

As I mentioned, it seems to be incorrect. The filter doesn't work when placed in the theme's `functions.php`.

Unless I'm missing something, you might want to consider correcting the documentation.

Thank you again for your time.

**Comment by kagg-design** [comment]
Yes, you are right - it cannot work from the theme's functions.php, as it is applied at `plugins_loaded` at -PHP_INT_MAX priority.

I will improve the documentation and maybe move the filter to the later event.

Thank you.
