### ISSUE TITLE
hCaptcha does not work on RapidMail form

### ISSUE THREAD

**Issue by RamazanKrty** [hCaptcha/hcaptcha-wordpress-plugin#304]
I have placed hCaptcha on the form I prepared with RapidMail. It seems to work correctly, but the form can be sent without hCaptcha being checked. I couldn't set it as a mandatory field. 

You can see the form on the following page:

https://www.qwertiko.de/newsletter/

![hCaptcha](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/104279786/e422a629-649b-4bcb-ac4f-8660d06182d2)

**Comment by kagg-design** [comment]
To make it work, you must add the code on the backend, verifying the hCaptcha. We do not support rapidmail so far. It has 300+ installations only. I see that you have inserted captcha manually, not using our plugin.

Please try to use our shortcode with auto, as [described](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/8fb8f6287cb9cf340637195bca8b3e50f7aae7ec/readme.txt#L125) in the readme.txt.

**Comment by kagg-design** [comment]
As I see, the `rapidmail` plugin makes the request to the `https://news.qwertiko.de/`, which is the rapidmail server, actually. It means that all the server-side checks must be performed on the rapidmail server side. With this approach, no hCaptcha, no Google reCaptcha, and nothing else would work with your form.

My recommendation is to change the email subscription plugin - it looks improperly designed.
