### ISSUE TITLE
js propagation on iphone with negative delay

### ISSUE THREAD

**Issue by AlexisKookline** [hCaptcha/hcaptcha-wordpress-plugin#312]
Hello hcaptcha team,

We have encountered a strange issue on iPhone (tested with iPhone on both Chrome and Safari).
Upon loading the first page, the first click (which initializes hcaptcha when selecting a negative delay) no longer triggers the intended event (opening a menu), as if the JavaScript propagation is not occurring.

This work fine if we disable the hcaptcha plugin.

We have temporarily resolved the issue by setting a positive the "Delay showing hCaptcha", but as mentioned, this affects the site's performance.

Have you any idea what can cause this issue and if there is a way to avoid it ? 

Have a great day,
Alexis.

**Comment by kagg-design** [comment]
It's hard to answer without seeing your page. Could you provide a link?

**Comment by kagg-design** [comment]
Closed as non-reproducible.
