### ISSUE TITLE
Hooking into WordPress' Comment forms before Akismet makes API calls

### ISSUE THREAD

**Issue by mudge** [hCaptcha/hcaptcha-wordpress-plugin#313]
We introduced hCaptcha onto a site in an attempt to head off spammy comments before they are processed any further, including being analysed by Akismet. However, it seems that Akismet uses the [`preprocess_comment`](https://developer.wordpress.org/reference/hooks/preprocess_comment/) hook while the hCaptcha plugin uses [`pre_comment_approved`](https://developer.wordpress.org/reference/hooks/pre_comment_approved/) which fires _after_ Akismet has made its API call.

Is there a way to restructure things such that hCaptcha fires _before_ Akismet, preventing the comment submission but also stopping it before it gets processed by Akismet potentially using up an API call?

**Comment by mudge** [comment]
Looking at Akismet's and WordPress' source code, it doesn't look like moving hCaptcha's check to `preprocess_comment` would particularly help unless you forcibly killed the script with `die()` (perhaps after rendering an error message) as the API for `preprocess_comment` doesn't let you return a `WP_Error` as with [`wp_allow_comment`](https://developer.wordpress.org/reference/functions/wp_allow_comment/).

Akismet has [a branch that does this if the "discard" option is true](https://github.com/wp-plugins/akismet/blob/0ad00d04967939652dc0fce242b3563da071d9da/class.akismet.php#L149-L154) which seems a little extreme but might be the only way to ensure no other plugin processes the comment data.

**Comment by kagg-design** [comment]
Thank you for reporting the issue. I have added the fix in [this commit](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/commit/dcb90dec8cd7936c1ae6709e96d6cb3dc4bf0ed7).

v3.9.0 will be released in days.

**Comment by mudge** [comment]
Thanks for the prompt response and fix.
