### ISSUE TITLE
latest hcaptcha plugin from wordpress is still having a lot of spam

### ISSUE THREAD

**Issue by sprappcom** [hCaptcha/hcaptcha-wordpress-plugin#317]
upgraded but spam still goes through for my multisite installation. how to resolve?

**Comment by e271828-** [comment]
@sprappcom please open a ticket with your sitekey via email to support@hcaptcha.com

**Comment by kagg-design** [comment]
@e271828- Could you check my last emails? It seems they went to spam... Thank you.
