### ISSUE TITLE
Add support for Divi forms

### ISSUE THREAD

**Issue by wuniversales** [hCaptcha/hcaptcha-wordpress-plugin#32]
I would like Divi support to be added, currently the forms only allow recaptcha to be selected.
https://www.elegantthemes.com/documentation/divi/spam-protection-providers/
I wish I could choose hcaptcha.
Regards

**Comment by e271828-** [comment]
Hi there, I'd suggest emailing them directly to add support.

**Comment by naharronak** [comment]
Hi @wuniversales,

Did you find a solution to the this?

**Comment by MaelImhof** [comment]
Hi @naharronak,

If you're still looking for a solution, please read [this other issue thread](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues/57#issuecomment-913582885). It may give you a way to use hCaptcha on your Divi website

**Comment by kagg-design** [comment]
@wuniversales @naharronak We have done it in V1.13.0, which will be published in a few days.
