### ISSUE TITLE
Problem with plugin...

### ISSUE THREAD

**Issue by apachoBR** [hCaptcha/hcaptcha-wordpress-plugin#321]
Hi!

We sometimes have a problem with the wordpress plugin. In this case it looks like shown on the screen shot. If I use it with a „Ninja Form“ and have two captcha fields at the same page, the second one always looks like that.

It seems, that clearing the browser cache solves it for the moment, but only that…

Do you have an idea?

Thanks!

best regards - Benjamin
![Bildschirmfoto 2024-02-26 um 13 35 17](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/48370726/9d32aa1c-9199-4c10-b8dd-b9a90bd04ccb)

**Comment by kagg-design** [comment]
Hi @apachoBR,

It is not an hCaptcha but a placeholder image. The hCapcha API script should normally replace it. Having it non-replaced means you have JS errors, which block the execution of all other scripts. Please open the browser Dev Tools console, and see JS errors there. They must be fixed to let hCaptcha work correctly.
