### ISSUE TITLE
Cannot use hCaptcha with forms that have file uploads such as Divi Contact Form

### ISSUE THREAD

**Issue by angelsvirkov** [hCaptcha/hcaptcha-wordpress-plugin#325]
Some forms such as Divi Contact Form have the possibility to upload a file with the form. While doing so, the underlying code might already send an ajax request, which would trigger the `ajaxSuccess` event with some arbritrary `settings.data` type. It looks like the JS assets at `./assets/js/1595567093/hcaptcha-divi.js` define an event listener which strictly expects that the `settings.data` has a callable property `includes`. The latter is not correct in the case of the file uploads. Therefore, the hCaptcha behaviour crashes and the whole form cannot be submitted.

**Steps to reproduce**
- Try to trigger an `ajaxSuccess` event where the `settings.data` is not a string but an object instead
or
- Use a form with file upload (e.g. Divi Contact Form) and upload a file to the form. 
The whole form will be stuck because of an uncaught exception

```
Uncaught TypeError: settings.data.includes is not a function
    at HTMLDocument.<anonymous> (hcaptcha-divi.min.js?ver=3.10.1:8:19)
    at HTMLDocument.dispatch (jquery.min.js?ver=3.7.1:2:40035)
```

I will try to submit a PR to fix this as it looks as a minor type guarding issue.
-> My attempt to solve the issue https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/326

**Comment by kagg-design** [comment]
Thank you, @angelsvirkov, for the report and the PR; it is appreciated!

I do not have the [Divi Contact Form Helper](https://www.elegantthemes.com/marketplace/divi-contact-form-helper/) plugin for testing. Could you share a zip file via email to info@kagg.eu?

**Comment by kagg-design** [comment]
I have changed the issue name. It is not a bug but an enhancement. Our code does not support so far the premium plugin Divi Contact Form Helper.

**Comment by kagg-design** [comment]
@angelsvirkov, thank you for providing the plugin for testing. I have fixed the issue in [this commit](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/commit/a8c2121c6d4d3f28f9d58ef7f8aa59c37e5c6f15).

**Comment by angelsvirkov** [comment]
Great, thanks. Is there any roadmap or plan for the release of v4?

**Comment by kagg-design** [comment]
> Great, thanks. Is there any roadmap or plan for the release of v4?

Yes, first days of April.
