### ISSUE TITLE
Doest't require solution on CF7

### ISSUE THREAD

**Issue by rzippert** [hCaptcha/hcaptcha-wordpress-plugin#33]
Hi,

Just installed the plugin on Wordpress, set up the API keys, enabled CF7 integration and went to test. The captcha shows up just fine and can be solved just fine, however submitting is not blocked if I ignore the captcha. It doesn't matter if the captcha is solved or not, I can submit the form just as before the plugin was installed:

![Captura de tela de 2020-07-05 00-54-32](https://user-images.githubusercontent.com/2091971/86525189-46a87280-be5a-11ea-92ea-39f3697dac9c.png)

Since there is no configuration available, I can't think about anything but to install a different plugin to test (or eventually trying to enable this manually).

Versions are hcaptcha 1.5.1, Wordpress 5.4.2 and Contact Form 7 5.2 (all up-to-date as of this writing).

There's nothing on the console, please let me know if there is any information that would help. I'm not a web dev. Pretty much in the dark here.

Thanks.

**Comment by donsony** [comment]
I also just noticed this... A fix would be great

**Comment by e271828-** [comment]
@donsony and @rzippert : this should now be resolved in 1.5.2.
