### ISSUE TITLE
WP is not defined at lostpassword action page with elementor-pro

### ISSUE THREAD

**Issue by dmardev** [hCaptcha/hcaptcha-wordpress-plugin#339]
Since 4.X, I am unable to show the hcaptcha at the _wp-login.php?action=lostpassword_ page, devtools displays the "wp is not defined".

![Screenshot_20240515_133138](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/57755166/4a98fa57-26f5-4f5d-9efd-abae0f2bc384)

Looking at the plugins, it seems related with "elementor-pro" (Elementor keeps 2 plugins, one free and the premium one, this is the premium). If i disable the plugin, the captcha seems to work again.

I'm not sure if is a problem with the elementor-pro plugin or the Hcaptcha integration but i can fix it adding as queue script dependency "wp-i18n" at HCaptchaHandler.php, inside the ElementorPro folder.

![Screenshot_20240515_135412](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/57755166/4859dacb-89ed-40aa-803b-0e2d0f7dc8bf)

Thanks!

**Comment by kagg-design** [comment]
Thank you for the report. I have fixed the issue; it will be released in v4.2.0 at the beginning of June.
