### ISSUE TITLE
Integration with WooCommerce block-based checkouts

### ISSUE THREAD

**Issue by gbakeman** [hCaptcha/hcaptcha-wordpress-plugin#341]
We'd like to be able to have hCaptcha integration with the WooCommerce block-based checkout experience - currently it doesn't seem to be showing up for us. I've also tried manually adding a Shortcode block in the block editor myself, however I can't figure out how to insert the block into the Checkout block group. Hopefully this is something that can be added!

Thanks in advance.

**Comment by e271828-** [comment]
@gbakeman do you have an example page? any other plugins installed?

**Comment by kagg-design** [comment]
@e271828- I see the issue, it appears in the latest WooCommerce version when a user enables a block Checkout. There are a lot of changes, including React events. I am on it.

**Comment by gbakeman** [comment]
@kagg-design That's it, thank you! How complicated do you think it will be for hCaptcha to integrate with the Blocks system?

**Comment by kagg-design** [comment]
It will be added to the next release at the beginning of July.

**Comment by gbakeman** [comment]
Wonderful, thanks!

**Comment by kagg-design** [comment]
It is done in v4.3.0, to be released at the beginning of July. Thank you for the idea!

**Comment by kagg-design** [comment]
v4.3.1 with the relevant fix is released.

**Comment by gbakeman** [comment]
Thank you!
