### ISSUE TITLE
Checkbox not loaded in Firefox in some scenarios - likely user plugin related

### ISSUE THREAD

**Issue by emp-irium** [hCaptcha/hcaptcha-wordpress-plugin#342]
Hello,

**We've recently implemented your plugin on one of our client websites** and it work properly in Edge, Chrome/Brave, but doesn't seem to work at all in Firefox. For example, when attempting to login to the WP dashboard via Firefox you cannot do it as it never shows the hcaptcha that otherwise is shown in other browsers. The same is true when trying to comment on forms - attempting to post a comment simply loads a new page and shows an error message.

**We've contacted your support and they forwarded us to your github.** They told us to include the HAR files of the site. Since HAR is not supported we printed it into PDF through Notepad++

[BRAVE-stelacavric.com.pdf](https://github.com/user-attachments/files/15781967/BRAVE-stelacavric.com.pdf)
[EDGE-stelacavric.com.pdf](https://github.com/user-attachments/files/15781969/EDGE-stelacavric.com.pdf)
[FIREFOX-stelacavric.com.pdf](https://github.com/user-attachments/files/15781970/FIREFOX-stelacavric.com.pdf)

**If you need any further information, let us know :)!**

**Comment by kagg-design** [comment]
I tried the page https://stelacavric.com/wp-login.php in Firefox and saw that it is working. It contains hidden forced hCaptcha, and I saw the hCaptcha upon the click on the Log In button:

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/b71cda55-2a05-4205-b0d6-85d2d0a98a00)

Could you clarify the issue?

P.S. Also, you can try to deactivate temporary some plugins on your website, to understand the culprit.

**Comment by emp-irium** [comment]
Hello,

Nope, still not working on our side. The pop up with images never shows and it just says incorrect username / password. 
We also visited this site here that uses hcaptcha: [Link](https://divisupreme.com/features/contact-form-7-module/)

All of the captchas in Firefox just look like this (image below), unable to be used (the same way it would look on the stelacavric website if the captcha wasn't set as hidden):

![Screenshot 2024-06-16 at 11-07-35 Contact Form 7 Module – Divi Supreme](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/172347353/08223f6a-8b32-4b73-8021-16fbb016c3b3)

We'll try again with disabling plugins,

**Comment by kagg-design** [comment]
I see the issue. Firefox does not react to mouse events and the hCaptcha API script is not loaded. As a workaround, set the "Delay showing hCaptcha, ms" to 0 or any positive value.

![image](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/assets/28291450/bd6b2940-c9d9-4fc1-ab0f-9935329d72a9)

A working example is on [my test site](https://test.kagg.eu/wp-login.php).

I will try to fix the Firefox issue.

**Comment by kagg-design** [comment]
Let us not discuss 3rd-party sites which we do not have access to. The https://divisupreme.com/features/contact-form-7-module/ page is built using wp rocket, whose lazy load feature often breaks the script loading sequence. See errors in the console: 

ReferenceError: wp is not defined (without wp global object nothing can work)
[hCaptcha] Callback 'hCaptchaOnLoad' is not defined. (broken script loading order)

**Comment by emp-irium** [comment]
Hello again,

We waited for the update and to check out the situation for quite some time - even waited for another update - but the issue persists. We are unable to verify that hcaptcha works while using Firefox. Even the login link you presented results in this screen:

![screenshot-issue](https://github.com/user-attachments/assets/0ee3a44d-d2c3-4545-ae70-24a5bebad22c)

In other words, the hcaptcha frame cannot be interacted with and thus makes it impossible to verify any login or comment reply through forms.

What else can be done?

**Comment by kagg-design** [comment]
Screenshot from the [link mentioned above](https://test.kagg.eu/wp-login.php) made right now:

![image](https://github.com/user-attachments/assets/7c7438ed-b1c7-40fd-96e5-0bcaf8a0df96)

Do you have errors in the Firefox console? Which version of Firefox do you use? Could you try to turn off all browser extensions?

**Comment by emp-irium** [comment]
**Hello, you were correct it was related to extensions within Firefox.** 

For some reason the "NoScript" plugin disabled the hcaptcha from working properly even though it was allowed within the options that can be accessed while on the main screen of Firefox. The only way to truly bypass it was to go within the settings of the NoScript extension and individually make hcaptcha "trusted".

On a side note, the extension Ghostery removes the notice on the bottom of the page "By proceeding you understand...", just to let people know if they experience the same thing. 

**🔎 To conclude:**

First, there was the issue with Firefox not properly reacting with delay as you said (resulting in hcaptcha not loading at all or being responsive on interaction), the second part was an extension issue within Firefox. 

Overall, it seems to work now 👏
Thank you a lot for taking the time to look into this issue 🤗

📧 Please look into the MailPoet issue we also opened - it started appearing with the latest update of both plugins (hcaptcha and mailpoet)
