### ISSUE TITLE
Integration with LearnPress

### ISSUE THREAD

**Issue by wyllyjon** [hCaptcha/hcaptcha-wordpress-plugin#346]
Hello ! 

It would be great if it was possible to integrate hCaptcha to the LearnPress forms.

Thank you !

**Comment by kagg-design** [comment]
I have installed LearnPress and think you need Captcha on the Checkout page, right? I cannot test it without having payment methods installed. Payment integrations, as far as I can see, are [paid addons](https://thimpress.com/learnpress-payment-settings-all-in-one-tutorial/) to LearnPress.

Can you share Stripe (better) or WooCommerce payment integration addon to my email info@kagg.eu?

Thanks.

**Comment by kagg-design** [comment]
Closed as non-reproducible.
