### ISSUE TITLE
Issue in 4.3.x: Vendor class inclusion failure

### ISSUE THREAD

**Issue by roelvanmeer** [hCaptcha/hcaptcha-wordpress-plugin#350]
Hi!

After updating the plugin to 4.3.0, we started seeing this warning:

`PHP Warning:  include(): Failed opening '/path/web/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/composer/../matthiasmullie/path-converter/src/Converter.php' for inclusion (include_path='.:/usr/share/php')`

Updating to 4.3.1 does not fix the issue. I noticed that the files from the matthiasmullie package are installed in the vendors dir (note the trailing s) instead of in the vendor dir, and that doesn't match with the entries in the autoload_classmap file.

Reverting to 4.2.1 makes the warning go away.

Could you please have a look at this?

Thanks! Roel

**Comment by kagg-design** [comment]
Hi @roelvanmeer,

Thank you for the report. I have fixed the issue in the 4.4.0 branch. A new version will be released at the beginning of August. You can try the intermediate [zip file](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/releases/tag/untagged-0051546be38d0b007c20) built from the branch. Please let me know if this works for you.

P.S. Explanation. The `matthiasmullie` packages are scoped and, therefore, placed in the `vendors` folder. The `vendor` folder must not have original libraries nor any mention of them in the original namespace.

**Comment by roelvanmeer** [comment]
The zip file link doesn't work, but I can wait for 4.4.0 to be released. Thanks for the fix!
