### ISSUE TITLE
Hcaptcha "forgot password"-integration breaks with "WPS hide login"

### ISSUE THREAD

**Issue by EorlBruder** [hCaptcha/hcaptcha-wordpress-plugin#351]
We run a wordpress-instance in which we move the path to the login-form with [WPS Hide Login](https://wordpress.org/plugins/wps-hide-login/). Let's say it's moved to "login".
In hcaptcha-integrations we activated "Wordpress -> Lost Password Form".
When a user then tries to reset their password, via "$wordpress_url/login/?action=lostpassword" the form shows without hcaptcha. When the user then enters their e-mail-address and clicks "receive new password", the form fails with the notice "Please complete the hCaptcha".

I poked a bit in the source code and found that the error lays in [LostPassword.php#45](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/79902b177240923efab52a037fdb281da7dc86b2/src/php/WP/LostPassword.php#L45). Here, the login-URL gets hardcoded to "/wp-login.php". 

I think either the mechanism should work without having to check for this URL (the login-mechanism seems to do so without issues) or it needs to somehow be possible to set this URL (e.g. by checking whether the URL is set through WPS Hide Login).

**Comment by kagg-design** [comment]
Hi @EorlBruder,

I have added integration with the WPS Hide Login plugin. The new v4.4.0 will be released at the beginning of August.
