### ISSUE TITLE
hCaptcha issue with MailPoet - Bad hCaptcha nonce!

### ISSUE THREAD

**Issue by emp-irium** [hCaptcha/hcaptcha-wordpress-plugin#354]
Hello again,

We've updated both hCaptcha and MailPoet to their latest versions and have this issue now within the MailPoet dashboard inside Worpdress:

![screenshot-issue-2](https://github.com/user-attachments/assets/544bef6b-8a35-47a2-bb25-ed18318337fc)

There are no visible settings or options that can be regulated to try and fix this notice, so we are posting this here on github as an issue. Everything worked before, now this error suddenly popped up. hCaptcha has a checkmark on its MailPoet integration for its forms. 

What can be done?

**Comment by kagg-design** [comment]
I have checked right now - and it works on my test site. Mailpoet, however, has several configurations. I used a block on the page.

Which one do you use?

**Comment by emp-irium** [comment]
An automation had been configured for all users who sign up to receive a weekly newsletter.
This signup works via Bloom (Divi - you can see it on bottom of homepage where it says "Pretplatite se na newsletter") and uses automation steps from MailPoet again to confirm, etc.

Right now nothing shows up in MailPoet as it keeps popping up those error notices about being unable to communicate with itself due to that "bad hcaptcha nonce". Sometimes, as we refresh or go through various MailPoet options, it also says "unknown error" or simply "bad hcaptcha nonce".

Worked well so far, last updates made this appear 🤔

We haven't touched or changed anything within the options of hcaptcha or mailpoet (except for that delay being set on 0 due to the firefox issue we had 🔎)

Let us know if you need any further info or access to the site 👍

**Comment by kagg-design** [comment]
Thank you for the additional information, but where is your homepage? Is it https://stelacavric.com/ ?

**Comment by emp-irium** [comment]
Ah, forgot to mention, yes 😅

**Comment by kagg-design** [comment]
I tried to guess what does it mean: "Bloom automation via Divi", but failed... Could you explain which steps I need to go through to see the issue? What to click, scroll, update page etc.?

Thank you.

**Comment by emp-irium** [comment]
The error occurs in the backend in Wordpress - no such notice is visible on the frontend.
As said, it started to occur after the last updates of MailPoet and hCaptcha were installed.

It would seem that there is some kind of communication error in MailPoet due to this hCaptcha nonce error 🤔

**Comment by kagg-design** [comment]
How can I reproduce the bug?

**Comment by emp-irium** [comment]
No idea, as it is happening on the backend after updating both plugins.
I can provide you with temporary access if you need 🔎

**Comment by kagg-design** [comment]
It would be super helpful. Please use my email info@kagg.eu.

**Comment by kagg-design** [comment]
Thank you for providing access. I have investigated and fixed the issue, created the 4.5.0-RC1 version of the plugin, and installed it on your site. All good now.

Please do not forget to update the stable version 4.5.0 at the beginning of August.
