### ISSUE TITLE
HCAPCTHA does not work in bbPress when logging in via shortcode

### ISSUE THREAD

**Issue by lgdelai** [hCaptcha/hcaptcha-wordpress-plugin#356]
When I create a page, and insert the bbPress login fields **using the native bbpress shortcodes,** hCapctha does not appear. 

See the shortcodes here:
Account
**[bbp-login]**
Display the login screen.

**[bbp-register]**
Display the register screen.

**[bbp-lost-pass]**
Display the lost password screen.
And here is the page with all the shortcodes. 
[](https://codex.bbpress.org/features/shortcodes/#account)

**Is it possible to make an adjustment where Hcaptcha also appears in forms inserted via shortcode?**

**Comment by kagg-design** [comment]
I have added this functionality. It will be released with 4.5.0 at the beginning of August.
