### ISSUE TITLE
Compatibility issue with Wordfence Security Plugin

### ISSUE THREAD

**Issue by techcvr** [hCaptcha/hcaptcha-wordpress-plugin#360]
"Recently, I encountered a compatibility issue with the Wordfence Security plugin. When I activate Wordfence, the CAPTCHA box on the WordPress admin login page disappears. I tried disabling the 2FA from the Wordfence login options, but the hCaptcha still doesn't appear. However, as soon as I deactivate the Wordfence plugin, the hCaptcha box works perfectly. Please refer to the screenshot below for a clearer understanding.

Wordfence Plugin Active
================
![image](https://github.com/user-attachments/assets/812d7b53-ac4b-4482-90f3-0865aae15b03)

Wordfence Plugin InActive
================
![image](https://github.com/user-attachments/assets/818401b8-9f80-43ff-9e89-f7bb2f68c755)

**Comment by kagg-design** [comment]
I cannot reproduce this. Could you provide a link to your site and hCaptcha System Info? Thanks.

**Comment by techcvr** [comment]
to reproduce this issue you have to install Wordfence plugin and then use hcapcha system on admin login page, 

this is my login page link - https://animeshopie.com/wp-admin/ with Wordfence plugin enabled

**Comment by kagg-design** [comment]
I did it, of course, and all good on for me. That is why I have asked for System Info.

**Comment by kagg-design** [comment]
Closed as not responded.
