### ISSUE TITLE
WordPress recovery mode

### ISSUE THREAD

**Issue by carlotafuro** [hCaptcha/hcaptcha-wordpress-plugin#364]
I noticed that the protection on the login form can be bypassed using the WordPress recovery login link which disables all plugins

/wp-login.php?action=entered_recovery_mode

In this mode it is possible to perform a brute force attack.

**Comment by RupW** [comment]
I don't know the functionality. How do you get a recovery login link? Do you have to be an administrator? Or at least control the administrator's email address? Can you turn off issuing recovery links?

**Comment by carlotafuro** [comment]
You can simply create a WordPress recovery mode link by following the link below to access recovery mode:

example.com/wp-login.php?action=entered_recovery_mode

All you have to do is replace example.com with your own site’s domain name.

In recovery mode WordPress disables all installed plugins, so you can perform brute force attacks without hcaptcha protection.

Recovery mode is a core WordPress feature that helps you fix fatal problems on your site by pausing problematic plugins or themes.

**Comment by kagg-design** [comment]
@carlotafuro Thank you for reporting the issue. However, there are some moments which should be clarified.

WP Recovery Mode does not deactivate all plugins. It just tries to "pause" the problematic plugin.

As @RupW correctly mentioned, things are so simple here. To enter the recovery mode, you need a token. However, the login procedure works without a token. Adding a GET parameter like `action=?entered_recovery_mode` prevents Captcha from being displayed and verified.

 It is an issue, and I fixed it already. The next version of the plugin will be released at the beginning of November.

**Comment by kagg-design** [comment]
@RupW Yes, you are right; hCaptcha is verified on the backend. Verification on the frontend makes no sense.

**Comment by carlotafuro** [comment]
I didn't find a page on the WordPress developer web site that documented Recovery Mode well.

I noticed that plugins aren't completely disabled, but I didn't understand what behavior occurs.

In any case, I noticed that login occurred even without solving hCaptcha.

**Comment by kagg-design** [comment]
I looked at the WP Core code and debugged the issue. The fix is done, now `/wp-login.php?action=entered_recovery_mode` requires solving hCaptcha.
