### ISSUE TITLE
Ninja Form Untagged releases

### ISSUE THREAD

**Issue by WesSylvain** [hCaptcha/hcaptcha-wordpress-plugin#365]
https://github.com/hCaptcha/hcaptcha-wordpress-plugin/releases/tag/untagged-ec09e09ac6f318ff3bed

Thank you for your feedback.
I can't download the RC2, I have a 404 back.

can you give me access?

Thank you

**Comment by kagg-design** [comment]
Apologies, here is an [accessible link to 4.7.0-RC2](https://drive.google.com/file/d/1GfEChNPCQuHmWBbbQxsR5cs64Jv4E85w/view?usp=drive_link). Kindly let me know. Thanks.

**Comment by kagg-design** [comment]
Closed as successfully tested here: https://wordpress.org/support/topic/ninja-form-bug/#post-18087730
