### ISSUE TITLE
Form in popu windows Vs hcaptcha

### ISSUE THREAD

**Issue by Vinks007Mp3** [hCaptcha/hcaptcha-wordpress-plugin#367]
Hi
I have a contact form included in a popup window which is launched by clicking a button (Enquire) on the main page but It seems that hcaptcha does not work when the form is included in a popup window: any suggestion welcome.

Site under Wordpress
I use WP Form and WP SMTP
I need to retrieve the main page ID and transmit it to the contact form so I know the item/ref that may interest the client.
So the question is: can I use hcpaptcha in my contact form which is in my popup windows ?
Thanks !

**Comment by kagg-design** [comment]
Hi,

Upon creation of the popup window, you should call window.hCaptchaBindEvents() to connect hCaptcha to the form. See a popup example in [this](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/10d376288a6d875f047075b3374764dfd5013261/assets/js/hcaptcha-login-signup-popup.js#L6) JS file.

However, your case could be more complicated, and for an exact answer, I have to see the page. Nevertheless, the main idea is always the same.

**Comment by Vinks007Mp3** [comment]
Hi Kagg
Thanks for taking the time to answer my message.
I'm not a developper therefore I won't be able to code it. I'll try recaptcha.
