### ISSUE TITLE
I cannot integrate hCaptcha to my WP site

### ISSUE THREAD

**Issue by Fran-nut** [hCaptcha/hcaptcha-wordpress-plugin#368]
I've downloaded the hCaptcha plugin and fill out the site and secret keys etc., but after I push the button "Check" there is this error: 

Site configuration error: Cannot communicate with hCaptcha server.

Why is there an error? First I've tried to connect reCAPTCHA, that didn't work as well. Then I've tried to connect hCAPTCHA directly in WP forms, that didn't work as well. And now I have an error connecting it with the hCAPTCHA plugin. 
Is there a problem with my site franziskawalther.ch?
Thanks for your help!

**Comment by kagg-design** [comment]
Yes, it is a problem with your server, which cannot send a request and receive a response. A kind of firewall prevents it. You should talk to your hosting provider.

**Comment by Fran-nut** [comment]
Unfortunately, the provider says, it's not a problem of the website and that everything runs OK. Any other idea?

**Comment by kagg-design** [comment]
A sort of usual answer from provider :). It is hard to say something without access to your site. Could you share at least the System Info from hCaptcha admin page?

**Comment by Fran-nut** [comment]
Now the provider said, there is this error in the server and the plugin:

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/franziskawalther.ch/https/wp-content/plugins/advanced-google-recaptcha/libs/ajax.php:159\nStack trace:\n#0 /var/www/vhosts/franziskawalther.ch/https/wp-content/plugins/advanced-google-recaptcha/libs/ajax.php(122): WPCaptcha_AJAX::verify_captcha()\n#1 /var/www/vhosts/franziskawalther.ch/https/wp-includes/class-wp-hook.php(324): WPCaptcha_AJAX::ajax_run_tool()\n#2 /var/www/vhosts/franziskawalther.ch/https/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()\n#3 /var/www/vhosts/franziskawalther.ch/https/wp-includes/plugin.php(517): WP_Hook->do_action()\n#4 /var/www/vhosts/franziskawalther.ch/https/wp-admin/admin-ajax.php(192): do_action()\n#5 {main}\n thrown in /var/www/vhosts/franziskawalther.ch/https/wp-content/plugins/advanced-google-recaptcha/libs/ajax.php on line 159', referer: https://franziskawalther.ch/wp-admin/options-general.php?page=wpcaptcha

They asked me, if the PHP settings matches the version. I do not know - what kind of settings do I need?
Greetings, Franziska

**Comment by kagg-design** [comment]
The message you provided appears in the Advanced Google Recaptcha plugin. We have no relation to it.
