### ISSUE TITLE
False URL Request

### ISSUE THREAD

**Issue by 1871vinayak** [hCaptcha/hcaptcha-wordpress-plugin#37]
hCaptcha always requests this URL `"wp-content/plugins/hcaptcha-for-forms-and-more/assets/css/admin.css"`
while being accessed and Gets an "HTTP 404 Not Found" error.
So to diagnose this problem I went through its Source Folder (The Plugin Folder `"hcaptcha-for-forms-and-more"`) but within the folder there's no such folder ,file or Path available named `"assets/css/admin.css"`.
What's the problem here please let me know.

> 
- WordPress version - 5.4.2
- hCaptcha for Forms and More - Version 1.5.3

**Comment by 1871vinayak** [comment]
@e271828- 
@kagg-design 
Please check the above issue #37 👆

**Comment by kagg-design** [comment]
@1871vinayak Thank you for reporting the issue. This file exists on github, but was not included into wp.org distribution package.

@e271828- Could you update trunk on wp.org? Thanks.

**Comment by e271828-** [comment]
> @1871vinayak Thank you for reporting the issue. This file exists on github, but was not included into wp.org distribution package.
> 
> @e271828- Could you update trunk on wp.org? Thanks.

Is there perhaps an issue with calling the distribution dir "assets" ? I believe we ran into this before.

**Comment by kagg-design** [comment]
@e271828- I have created https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/38.

**Comment by 1871vinayak** [comment]
@e271828- Thanks for merging the Fix #39 .
Please update the plugin in the WordPress.org so that all the user receives the update. 
👍

**Comment by e271828-** [comment]
Now solved.
