### ISSUE TITLE
hCaptcha Within a Parent iFrame

### ISSUE THREAD

**Issue by jcruz-ieeecs** [hCaptcha/hcaptcha-wordpress-plugin#371]
We are seeing an issue when using the hCaptcha verification widget where the challenge popup will display in the middle of the page, instead of near the hCaptcha box itself.

We are developing a headless WordPress site, using the NextJS framework as the front end.

In WordPress we are using the hCaptcha plugin along with the hCaptcha Pro version to verify/protect our site Gravity Form forms.

Our Gravity Forms are rendered on the WordPress side, example:

   https://next-dev.computer.org/general-gravity-form-render/?form=86

In the NextJS side, we are using an iFrame to view that WordPress page, example:

   https://next-dev-website.computer.org/gravity-form-embed-flexible-content-test

You'll notice that on the WordPress URL, the challenge popup will display near the hCaptcha widget.

In the NextJS URL, you'll see the challenge popup appear at midpoint of the iFrame, with the browser scrolling the user up to where it has located the challenge.

We've tried to override the CSS of the challenge <iframe> as well as its parent &lt;div&gt; elements.   We've also tried to manipulate the location of the challenge popup using a variety of javascript solutions.

In all cases, there is something (JS?) that is setting the challenge <iframe> parent &lt;div&gt; to contain a dynamically calculated "top" CSS attribute, (as that popup parent &lt;div&gt; has "position" of "absolute").

Has anyone encountered this issue before?   

Any idea how to override, or set, the location of the challenge popup within an iFrame?

We would like it to be displayed as it normally would, next to the hCaptcha element itself.

Thanks

Jon

**Comment by kagg-design** [comment]
The hCaptcha main JS script is taken from the hcaptcha.com site, and the WordPress plugin has no influence on this code. We just provide integrations with WordPress plugins. We do not have access to this main JS script code.

You should reach hCaptcha support on the [hcaptcha.com](https://www.hcaptcha.com/contact-us).

Thanks.
