### ISSUE TITLE
Error: The Captcha is invalid.

### ISSUE THREAD

**Issue by GalaxyTheoryz** [hCaptcha/hcaptcha-wordpress-plugin#41]
I have attempted to install hCaptcha on my wordpress site with the correct Site Key and Secret Key. I keep getting 'Captcha Invalid' when I have completed it correctly and I have also disabled all plugins. Not too sure why this is happening but it is preventing users from logging into my website.

**Comment by e271828-** [comment]
Hi, is this for the basic WP integration?

**Comment by GalaxyTheoryz** [comment]
Hi, yes, it is. I keep getting Error: Captcha Invalid with all other plugins disabled.

**Comment by e271828-** [comment]
What WP version? I just tried the latest version of our plugin on WordPress 5.4.2 with no other plugins installed, and selected:

```
   Enable hCaptcha on Login Form
   Enable hCaptcha on Register Form
   Enable hCaptcha on Comment Form
   Enable hCaptcha on Lost Password Form
```

Everything worked as expected. Please double-check your sitekey (looks like a UUID4) and secret (starts with 0x).

**Comment by GalaxyTheoryz** [comment]
Hi, I am using the latest WP Version. I've just tried a different hCaptcha plugin and am getting the same error. I have also disabled all plugins in troubleshooting mode. I might try a different WP installation.

**Comment by shaunwarman** [comment]
May want to watch out for javascript interpreting the 0x as hex which would lead to your site key being interpolated as some random number instead of your actual site key.

**Comment by e271828-** [comment]
@shaunwarman do you see any examples of this in the code?

**Comment by dltmurphy** [comment]
This is also affecting 2 sites i have taken work on for. It passes the hCaptcha window but when submitting it gives the invalid error

**Comment by dltmurphy** [comment]
Mine seem to be getting blocked by my Wordfence plugin. I'm looking into how to allow hCaptcha to run without being blocked and will post here when it works

**Comment by hollowaykeanho** [comment]
I reproduced this problem (too frequent until it is unusable, even on easy level). Given 2 of my beta testers done it correctly, hCap still give invalid results. 

No code customization. Just plugin install, integrate and use.

**Comment by pwnoobz** [comment]
I can confirm the problem persists in the current version with the latest WP version.

**Comment by kagg-design** [comment]
How to reproduce this issue? Or, could you provide the access to the site where you have the issue?

**Comment by pwnoobz** [comment]
> How to reproduce this issue? Or, could you provide the access to the site where you have the issue?

I am sorry to inform you that my posting is old. By the time you answered me, the issue was already fixed but thanks for paying attention!
