### ISSUE TITLE
possible to have native enabling for brizy , contact form 7 and beaver builder plugin?

### ISSUE THREAD

**Issue by gitmko0** [hCaptcha/hcaptcha-wordpress-plugin#45]
possible to have native enabling for brizy , contact form 7 and beaver builder plugin?

it'll be dream come true! when we can expect the native auto enabling of these above?

**Comment by e271828-** [comment]
Hi, I'd suggest opening a PR or emailing those plugin authors: this plugin is entirely user-developed.

**Comment by kagg-design** [comment]
We have added support for CF7 and Beaver Builder. Are you still interested in Brizy? If so, please open a new issue.

Thank you.
