### ISSUE TITLE
The only problem with this plugin is it loads in every page / post on wordpress

### ISSUE THREAD

**Issue by gitmko0** [hCaptcha/hcaptcha-wordpress-plugin#48]
The only problem with this plugin is it loads in every page / post on wordpress
possible to make it so that it will only appear on pages / post that have the detection of contact form 7 / woocommerce page / form on? 
can anyone provide the code for this only? i'm only using contact form 7 and woocommerce.

**Comment by e271828-** [comment]
Hi, PRs welcome :)

**Comment by mainserv** [comment]
Same technique -> reCaptcha seems to be working :
`add_action('wp_print_scripts', function () {
	global $post;
	if ( is_a( $post, 'WP_Post' ) && !has_shortcode( $post->post_content, 'contact-form-7') ) {
		wp_dequeue_script( '**hcaptcha-script**' );
	}
});`

**Comment by kagg-design** [comment]
@mainserv it not a solution. What if CF7 form is in the sidebar? What if it is in the header or footer? In a popup?

Same questions are related to forms in other compatible plugins.

**Comment by kagg-design** [comment]
From version 1.10.1, the hCaptcha script runs only if the hCaptcha form was used somewhere on the page.
