### ISSUE TITLE
Add support for Gravity Forms

### ISSUE THREAD

**Issue by jeremiahbenes** [hCaptcha/hcaptcha-wordpress-plugin#49]
The plugin does not support [http://gravityforms.com/](Gravity Forms). It would be awesome if there were drop in support for this plugin.

**Comment by ben-dietrich** [comment]
Second that request! We use Gravity forms on too many sites to count and Akismet only takes us so far.

**Comment by erikjoling** [comment]
I agree, though there seems to be a different plugin which solves this: https://wordpress.org/plugins/gf-hcaptcha/

**Comment by ngrhd** [comment]
Third request!

**Comment by monaalexandra** [comment]
Yes, please!
I thought since Gravity Forms is sich a wildly used form plugin it is already supported, but just found out today that it's not… 😔

**Comment by kagg-design** [comment]
Gravity Forms support was added in v1.15.0 and will be published soon.
