### ISSUE TITLE
Possible to add hcaptcha to DIVI theme without needing to ask them to support hcaptcha?

### ISSUE THREAD

**Issue by gitmko0** [hCaptcha/hcaptcha-wordpress-plugin#57]
I know it's not difficult. I know you have mentioned to Divi to ask them to support hcaptcha but can we do it without waiting for them?

**Comment by e271828-** [comment]
Yes, if you open a pull request here with the change we will merge it: that's how all the existing plugins/themes got their support.

**Comment by 1clapmac** [comment]
Hi, I'm also interested..because of this Situation :

I'm using Divi creative agency  (elegant themes )  through Divi version Version : 4.8.1  at infomaniak. I have an account hcaptcha (that is is API-compatible with reCAPTCHA). I have the sitekey and secret implemented in the divi form ("Use A Spam Protection Service" activated on ‘yes’ ) and the account activated on the server side for :
- Enable Ninja Forms Addon
- Enable Contact Form 7 Addon
- Enable hCaptcha on Login Form
- Enable hCaptcha on Register Form
- Enable hCaptcha on Comment Form
- Enable hCaptcha on WPForms Lite
- Enable hCaptcha on WPForms Pro
- Enable hCaptcha on Jetpack Contact Form 

 1. hcaptcha appears, and works on the login access WP page ( wp-login.php )
 2. but nothing happens when button submit of the **divi form** is being hit

How do you operate your 'pull-request' towards Divi ?

**Comment by MaelImhof** [comment]
The support of Divi is more difficult as Divi does not follow all the Wordpress coding standards. What I mean is that there are **[no hooks to filter](https://www.elegantthemes.com/documentation/developers/hooks/)** either contact form displaying nor contact values processing.

I was thinking of a way to add Divi support, and the only ones I currently see are :

1. [Creating a Divi custom module](https://www.elegantthemes.com/documentation/developers/divi-module/), maybe inheriting from the Divi contact form
2. Doing some tricky thing with page loading, stop loading if the captcha is not correct... Na it would not work

To add Divi support, we need :

- [ ] A way to alter the contact form displaying, to add the hCaptcha field
- [ ] A way to alter the contact data processing server-side, to check the hCaptcha validity and process only if the field is valid

If anyone has a better idea maybe we can add support while Divi is making it easier (I hope)

**Comment by seamive** [comment]
Any updates on this? There is a Divi Module named "Supreme Contact Form 7" and "Divi Contact Form" I guess both can use hCaptcha inside it.

**Comment by e271828-** [comment]
> Any updates on this? There is a Divi Module named "Supreme Contact Form 7" and "Divi Contact Form" I guess both can use hCaptcha inside it.

You can try the shortcode:

https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/24db1998eee98e9c1472da26928fc93a64ca1833/readme.txt#L57

**Comment by seamive** [comment]
Well, if we see the settings, hCaptcha does support Contact Form 7 but how to make it work with the module of Divi Supreme itself? We tried adding the hCaptcha and seems like it shows both hCaptcha and reCaptcha at the same time.
We added [hcaptcha] directly inside contact form 7

**Comment by kagg-design** [comment]
@gitmko0 It was extremely difficult. Divi has a not-extendable code, without any hooks allowing 3rd parties to modify the form. Moreover, the theme controls the content of the form and compares it to what was created by its own PHP code. I had to spend hours debugging and invent several tricks to circumvent all of that hurdles.

**Comment by kagg-design** [comment]
@gitmko0 @1clapmac @MaelImhof @seamive We have done it in V1.13.0, which will be published in a few days.

**Comment by 1clapmac** [comment]
I don't know if that would help you, but I have found a solution to have hCaptcha work in Divi for WP with Form7  : 
1. open a hcaptcha account
2. install "**hCaptcha extension WP**"
3. check box "open with form 7" in settings
4. enter key and secret key
5. install **Contact Form 7 WP** and activate extension Contact Form 7
6. THEN install **Contact Form 7 Styler for Divi** (don't make subscription)
7. in WP, go to DIVI settings > CF7 styler
8. Activate (checkbox) "Contact form 7 Grid Builder"
9. In Contact Form 7 > Contact ( Form Tab) > code your form such as : 
<label> Votre nom
    [text* your-name] </label><br/>
<br>.... etc...
10. same with "email TAB", code mail structure (see on internet the use of Form 7 Styler for Divi )
11. Create your contact page in DIVI by selecting 'new module' > WP 7 Form > choose the name of the form created with styler.. then validate end save
12. When page is displayed, hcaptcha will appear on you form.. (see contact page on _1clap.com_ )

Hope this helps :)

**Comment by kagg-design** [comment]
@1clapmac we are not interested in offering our users to install two additional plugins (CF7 and CF7 styler) just to be able to send a contact form from Divi. Also, your solution is based on using Contact Form 7.

Here, in this thread, we discussed the ability to use the native Divi Contact Form module.

It works now in the latest V1.13.0, published today.

**Comment by seamive** [comment]
So it's working fine with Divi builder with v1.13.0?
