### ISSUE TITLE
Captcha verification before username verification

### ISSUE THREAD

**Issue by aledef** [hCaptcha/hcaptcha-wordpress-plugin#58]
Captcha error is shown only if username is good, otherwise wrong username notice is shown.
In other words captcha is verified AFTER username verification, whilst it should be verified BEFORE.
This would enhance effectiveness against brute force attacks.

**Comment by kagg-design** [comment]
In which scenario? WP login page or some plugin?

**Comment by aledef** [comment]
WP login page

**Comment by kagg-design** [comment]
I have checked the idea, it is not consistent. Anyway, the result of the captcha MUST be checked on the backend, and we do the same. In which order to check on the backend, user first or captcha first - does not matter.

You can use, however, the recently introduced invisible hCaptcha, which shows the challenge (pictures) by JS upon the attempt of sending the login form. It does not load the server at all.

This behaviour can be avoided by very smart or specially designed bots, so any way we check captcha results on the backend. But I hope that invisible hCaptcha behaviour will reject most of the bots using the browser.
