### ISSUE TITLE
How to integrate to contact form 7

### ISSUE THREAD

**Issue by yulianto8327** [hCaptcha/hcaptcha-wordpress-plugin#59]
Do you have any documentation how to integrate this with contact form 7? It's already enabled for contact form 7, but it's not showing the hcaptcha. Do I need to add code to the contact form 7?

**Comment by mainserv** [comment]
Go to hCaptcha settings and **_Enable Contact Form 7 Addon_** ;)

**Comment by yulianto8327** [comment]
> Go to hCaptcha settings and **_Enable Contact Form 7 Addon_** ;)

it's already enabled but still not working

**Comment by cristiancs** [comment]
In my case it didn't work because i had installed w3 total cache installed and didn't cleared the cache, also make sure you put your site and secret key.

Finally, if it still doesn't appears, you could add

[hcaptcha] to your form.

**Comment by kagg-design** [comment]
`[cf7-hcaptcha]` is added automatically 'on the fly' to the Contact From 7. I have fixed a similar issue, please check the problem with the latest plugin version 1.9.0.
