### ISSUE TITLE
hCaptcha error when refreshing Contactform 7

### ISSUE THREAD

**Issue by kyaniheessels** [hCaptcha/hcaptcha-wordpress-plugin#62]
I have the add-on installed for Contactform 7, and it works fine except for one bug I came across.

When I fill in the form the wrong way, for example filling in a non valid email address, and then prove that I'm human after which I submit the form. I get the notification that the email isn't okay... so when I correct that the hCaptcha box stays checked so I submit try to submit the form. But then the form gives an error saying that the Captcha is invalid.

I came across someone else who also ran into this but I haven't found a solution yet. (https://wordpress.org/support/topic/refresh-hcaptcha-on-form-error-in-contact-form-7/)

Here's the link to the form that I made:
https://dev2.andersdev.nl/kontakt/?lang=de

![image](https://user-images.githubusercontent.com/31549205/105364629-a8b1a500-5bfd-11eb-8d96-e5549128591d.png)

**Comment by kagg-design** [comment]
I believe it is the same as for issue #72 and was fixed in 1.9.0. Could you check?

**Comment by kyaniheessels** [comment]
I've updated the plugin and checked but it doesn't seem to have fixed the issue.

**Comment by kagg-design** [comment]
Thank you for the explanation, I got the problem, will try to fix it.
