### ISSUE TITLE
Feature Request: enable on WooCommerce Checkout Form but only for guests

### ISSUE THREAD

**Issue by djramones** [hCaptcha/hcaptcha-wordpress-plugin#66]
It would be very nice to present the captcha to unauthenticated users (so as to protect against spam orders), but not to those customers who have already made the effort to sign-up for an account (which is bothersome and can reduce conversions).

**Comment by comedyaddict** [comment]
Agreed, that would be a beneficial option IMHO.

**Comment by djramones** [comment]
It seems that all that's needed to achieve this (if it's okay to make this the default behavior for this particular feature/module), is to wrap the `add_action` calls in [`wc/wc-checkout.php`](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/db9c04ed2efaf1c208ab6717e5db5110c631df4f/wc/wc-checkout.php) with `if ( ! wp_get_current_user()->exists() ) { ... }`.

Disclaimer: I'm new to WordPress dev so I have no idea if this is a sound solution, and if this fits the plugin's architecture. As a hack, it works though.

**Comment by comedyaddict** [comment]
Good point; that's what I would have done when I was doing php development in my own applications if I needed this.  I just haven't had the time to learn Wordpress dev. Hopefully this file doesn't get updated too often ;-) Thanks for the code, it's a good workaround that hopefully the plugin developer adds.

**Comment by comedyaddict** [comment]
Actually this has method has some unintended consequences. It appears that if you enable the hcaptchta on your checkout page, it still injects code that tries to verify it. The above code effectively only hides the box during checkout, but the site appears to think it actually is there.

**Comment by djramones** [comment]
> Actually this has method has some unintended consequences. It appears that if you enable the hcaptchta on your checkout page, it still injects code that tries to verify it. The above code effectively only hides the box during checkout, but the site appears to think it actually is there.

Sounds like you added the code snippet for the first `add_action` call (the one for `hcap_display_wc_checkout`) but not for the second one (the one for `hcap_verify_wc_checkout_captcha`). The first is what displays the captcha box to the user, the second is what makes the backend look for a valid captcha in form submissions before allowing WordPress to accept the data. I've tested this on an actual public WordPress install so I'm quite sure it works.

**Comment by djramones** [comment]
The new v1.10 release adds a “Turn off when logged in” setting, and that addresses this request.
