### ISSUE TITLE
Probably broke a lot of Wordpress sites with 1.8.0

### ISSUE THREAD

**Issue by BentHaase** [hCaptcha/hcaptcha-wordpress-plugin#75]
The few minutes `1.8.0` was / is live seems to have broken one of our pages which has plugin auto-updates running.

I know this is not helping you, I can fix this on our side but there might be quite a few WP sites broken...! :astonished: Just a heads up.

**quickfix for any future timetraveler:**

### be careful with `rm` :warning:

Simply remove the plugin from your plugins directory.

```bash
# rm -r wp-content/plugins/hcaptcha-for-forms-and-more
```

**Comment by e271828-** [comment]
Hi @BentHaase , sorry about that. It seems like only a small number of sites auto-upgraded before we pushed the 1.8.1 hotfix. 

Humorously enough, the issue was related to efforts to add 100% test coverage and full integration tests in 1.8.0 series.
