### ISSUE TITLE
Not fully working with CF7 - Mar-2021

### ISSUE THREAD

**Issue by blaircomm** [hCaptcha/hcaptcha-wordpress-plugin#78]
If the user does not even fill in the H-Captcha on the form, the page will refresh anyway ass if the message was sent, without a mandatory error message. But, the message will not be sent. This leaves the user thinking the message was sent when it wasn't. 

It works when it is filled in, but does not inform the sender that the message has been successfully sent.

Both cases ender the plugin unworkable in CF7 for now.

**Comment by e271828-** [comment]
@kagg-design when you have a chance, please look. @blaircomm , we always suggest using native hCaptcha integrations like WPForms if you can, as CF7 or any other plugin can make changes on their end.

**Comment by kagg-design** [comment]
I have fixed similar issue 72, and with the latest version of the plugin 1.9.0, I cannot reproduce the problem. @blaircomm could you provide further instructions?

**Comment by blaircomm** [comment]
We have decided to redo our forms using WPForms when time allows. Too much hassle to troubleshoot CF7. Thanks for the feedbck.
