### ISSUE TITLE
Support for Caldera Forms

### ISSUE THREAD

**Issue by albridi** [hCaptcha/hcaptcha-wordpress-plugin#79]
Hi there :) !

I would like to use hCaptcha with my forms, made with Caldera.

Do you plan to add support for this plugin?

Thanks in advance.

Kind regards.

**Comment by e271828-** [comment]
Hi @albridi , you can open a PR here, or ask Caldera to add native support.

**Comment by albridi** [comment]
> Hi @albridi , you can open a PR here, or ask Caldera to add native support.

Thanks for help :) . I'll open a PR.

Regards.

**Comment by kagg-design** [comment]
The plugin is closed so we won't proceed with the request.
