### ISSUE TITLE
Captcha failed

### ISSUE THREAD

**Issue by wiwi-websolutions** [hCaptcha/hcaptcha-wordpress-plugin#83]
When using the plugin it sometimes fails without any error code, it just says "captcha failed", while the captcha is marked as completed. Is there any way for us to check what's causing this issue? 

Example of the error: https://images2.imgbox.com/0e/4f/oDG6vRr1_o.png

We tried the following:
- disabling all caching methodes
- remove all other scripts
- different domains/websites
- latest WordPress and plugin version

**Comment by e271828-** [comment]
Do you have any logs from the backend?

**Comment by wiwi-websolutions** [comment]
> 
> 
> Do you have any logs from the backend?

Does the plugin write any logs, or do you mean server logs?

**Comment by pwnoobz** [comment]
I am having the exact same problem and I'm also asking if the plugin writes any error logs.

**Comment by ForNesiaFreak** [comment]
Does anyone solve this problem ? I am having the exact same problem in my 3 website

**Comment by Peter9936** [comment]
Same problem here. Have the captcha activated on the login page of WooCommerce, but when someone tries to login, the captcha marks as completed (no error is displayed, not even in console). After submitting the login form, it refreshes the page and does nothing. This needs to be fixed ASAP. Disabling the captcha solves the problem.

**Comment by pwnoobz** [comment]
> Does anyone solve this problem ? I am having the exact same problem in my 3 website
> 
> edit, i solved my problem, sorry

Can you please share how?

**Comment by kagg-design** [comment]
@wiwi-websolutions @pwnoobz @ForNesiaFreak @Peter9936 can you confirm the issue with the latest version of our plugin? If yes, how can I reproduce it - step by step?

**Comment by pwnoobz** [comment]
Well, after I updated a bunch of things and worked on my server caching it's working as intended. Thanks for following this disccusion. I love your work with that plugin. It saves me from the nasty spam! Please make a donation option more obvious on the backend for the people who want to donat but not a pop up that will flash in our faces. Thanks again!

**Comment by kagg-design** [comment]
@pwnoobz Thank you for your kind words. We are happy to bring value to our users.
