### ISSUE TITLE
Error: Please complete the captcha. Woocommerce 5.1.0 Login Form

### ISSUE THREAD

**Issue by teddyubob** [hCaptcha/hcaptcha-wordpress-plugin#87]
Hi,
On WordPress Version 5.7 
Hcaptcha wordpress plugin 1.9.0 gives an Error: "Please complete the captcha" on woocommerce 5.1.0 login form even when the captcha is solved correctly. 

This issue only occurs when either "Enable hCaptcha on Login Form" or "Enable hCaptcha on WooCommerce Login Form" option is checked and user try to login on site.com/my-account/

**Comment by e271828-** [comment]
@kagg-design can you take a look?

**Comment by JXGA** [comment]
Also experiencing this issue. 

Disabled the plugin by renaming the folder in `wp-content/plugins`

**Comment by e271828-** [comment]
> Also experiencing this issue.
> 
> Disabled the plugin by renaming the folder in `wp-content/plugins`

You should also be able to downgrade to 1.8.1.

**Comment by teddyubob** [comment]
> You should also be able to downgrade to 1.8.1.
@e271828- is downgrading Hcaptcha plugin 1.9.0 to 1.8.1 the only solution or is there an update expected? Thank you
