### ISSUE TITLE
I found a translation error

### ISSUE THREAD

**Issue by lgdelai** [hCaptcha/hcaptcha-wordpress-plugin#88]
Hi.

I found a translation error:

When I try to send a form without selecting the checkbox, I receive the message in English, not in Portuguese.

"The Captcha is invalid"

I inform that I already added the code "pt" in the field "Override Language Detection (optional)"

**Comment by e271828-** [comment]
Hi, you can add translations here: https://translate.wordpress.org/projects/wp-plugins/hcaptcha-for-forms-and-more/

**Comment by lgdelai** [comment]
All Translations Done, 

Thanks
