### ISSUE TITLE
Plugin injects the verification box even inside unnecessary <form> tags

### ISSUE THREAD

**Issue by nirmitha-mw** [hCaptcha/hcaptcha-wordpress-plugin#89]
Hi!

`I’m using hCaptcha in Jetpack contact form.
Looks like hCaptcha plugin target unnecessary < form > (s) in my website & inject the verification box with all of it.
How to fix this? How to target Jetpack contact form only?

hCaptcha showing inside the search button. Please check :- https://snipboard.io/Uq2LzM.jpg
My contact form is working fine. :- https://prnt.sc/10zi1ov

hCaptcha settings :- https://snipboard.io/cKSw7T.jpg

If you need a live example to test, please let me know.

**Comment by kagg-design** [comment]
Do you use this plugin? https://jetpack.com/upgrade/search/ If yes, I need it for testing. Please contact me via https://kagg.eu/en/contacts/

**Comment by kagg-design** [comment]
I cannot confirm this,

I have installed the official [Jetpack Search addon](https://jetpack.com/support/search/).

Please see the screenshot: 

![image](https://user-images.githubusercontent.com/28291450/134056133-ea6a5ad1-a966-45d7-9c06-8ca5d773d343.png)

**Comment by kagg-design** [comment]
I have finally understood what kind of form is impacted by the plugin. It is not a Jetpack Search. It is a simple standard search form that has to be inserted into the content.

Issue fixed in V1.13.0, which will be published soon.
