### ISSUE TITLE
Version 1.9.1 is not available in the WordPress Plugin Directory

### ISSUE THREAD

**Issue by lukasleitsch** [hCaptcha/hcaptcha-wordpress-plugin#90]
On GitHub you released the [Version 1.9.1](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/releases/tag/1.9.1). This version contains major changes for the ContactForm7 Integration. In the WordPress Plugin Directory [the latest version of this plugin is 1.9.0](https://wordpress.org/plugins/hcaptcha-for-forms-and-more/).

When do you plan the release of 1.9.1 in the WordPress Plugin Directory?

**Comment by e271828-** [comment]
1.9.2 released.
