### ISSUE TITLE
Divi theme hCaptcha issue

### ISSUE THREAD

**Issue by naharronak** [hCaptcha/hcaptcha-wordpress-plugin#91]
I am using the Divi theme (https://www.elegantthemes.com/gallery/divi/) for my WordPress. I am trying to add hCaptcha in my contact form, but what I found is that hCaptcha does not work/support the Divi contact form. Can you please look into this?

**Comment by MaelImhof** [comment]
Hi @naharronak,
As I mentioned in the first thread you opened, you may find a solution in [this other issue thread](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues/57#issuecomment-913582885).

Have a nice day !

**Comment by kagg-design** [comment]
@naharronak We have done it in V1.13.0, which will be published in a few days.
