### ISSUE TITLE
Woocommerce login error

### ISSUE THREAD

**Issue by djdadspins** [hCaptcha/hcaptcha-wordpress-plugin#92]
I had Hcaptcha enabled on woocommerce login and registration enabled.  After completing the captcha correctly and clicking login, I get "Error: Please complete the captcha".  I disabled captcha on the login but left enabled on registration and still get the error.  

Woocommerce 5.2.2
Wordpress 5.7.1

**Comment by JXGA** [comment]
Same as this: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues/87

**Comment by e271828-** [comment]
Closing as dup
