### ISSUE TITLE
Feature request: Set keys and options in wp-config.php

### ISSUE THREAD

**Issue by apeman76** [hCaptcha/hcaptcha-wordpress-plugin#93]
I have a multisite running and would love to be able to set the keys and options through my wp-config.php so I wont have to go through every subsite and edit it.
Is this possible?

**Comment by e271828-** [comment]
PRs welcome :)

**Comment by joostdekeijzer** [comment]
I've created a private plugin with some changes I need for the hCaptcha plugin, including setting constants in wp-config. See https://gitlab.com/dkzr-wordpress/plugins/dkzr-hcaptcha-enhancements

I can create a pull request to do something simular. I do itch to convert the hCaptcha settings screen to the WordPress Settings API (https://developer.wordpress.org/plugins/settings/settings-api/). Is there an opinion about that :)

A next step could be to add 'Network settings' for hCaptcha.

**Comment by e271828-** [comment]
@joostdekeijzer certainly, Settings API would be a reasonable change. Please open a PR against this repo with any changes you'd like to see. Most of them do get merged in some form.

**Comment by kagg-design** [comment]
@apeman76 I have added the ability to set options network-wide on multisite:

![image](https://user-images.githubusercontent.com/28291450/192159003-799ca184-c44e-4959-a8a5-6aadbd205e8b.png)

@joostdekeijzer Now settings screens (one of them is above) are using WP Settings API.

**Comment by joostdekeijzer** [comment]
Wow, great work @kagg-design

**Comment by kagg-design** [comment]
Thank you, @joostdekeijzer, for the plugin. I have added the code to avoid the layout shift during hCaptcha loading.
