### ISSUE TITLE
Add support for Profile Builder (Profile Builder forms ignore hCaptcha even when using [hcaptcha] shortcode)

### ISSUE THREAD

**Issue by KZeni** [hCaptcha/hcaptcha-wordpress-plugin#99]
~Currently, enabling hCaptcha for the login form & everything via this plugin while then using Profile Builder (https://wordpress.org/plugins/profile-builder/) to restrict the content of a site (and show a login form on the page instead of the content) has the login form shown without hCaptcha being shown. Then, submitting the login form says:~
>~Error: Please complete the captcha.~

~So it seems like the server-side protection is there & it's just a matter of the login form (among the other forms Profile Builder offers) not outputting the actual hCaptcha element for verification when using Profile Builder in this way.~

***Edit:** [See the comment below this](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/issues/99#issuecomment-1548193126) for an update since this server-side error mentioned above appears to no longer be happening while it still isn't working as expected.

Meanwhile, https://www.cozmoslabs.com/40120-adding-recaptcha-wordpress-register-login-lost-password-forms-profile-builder/ (among other places) shows that Profile Builder currently supports reCAPTCHA so hopefully adding hCaptcha support won't be too involved.

I've turned off the hCaptcha protection of the login form as a momentary workaround for now (with me not wanting to use reCAPTCHA instead of hCaptcha.) It's been tested and shows this avoids the issue. Also, I personally just have Profile Builder for the login form for protected content while things like Forgot Password, Register, etc. use the standard WordPress page for handling that so those have been left as using hCaptcha without issue. That being said, Profile Builder does have `[wppb-login]`, `[wppb-register]`, `[wppb-recover-password]`, and other shortcodes that could/should be accounted for in addition to the login form protection just in case a site uses one of those as well.

I'd love to see Profile Builder support added for its forms as hCaptcha really is preferred over reCAPTCHA at this point. I'd love to re-enable this login protection once the support has been added (again, with me personally not using Profile Builder for register, lost password, etc. currently while others might.)

Also, I came across https://wordpress.org/support/topic/no-support-for-wp-profile-builder/ which shows I'm not the only one hoping for this support to be added.

I’ve then also posted this on WP.org support forum for further visibility for those that might be looking for it: https://wordpress.org/support/topic/add-support-for-profile-builder-pb-forms-break-when-enabled-via-hcaptcha/

Thanks for the great plugin & service,
Kurt

**Comment by KZeni** [comment]
Okay, I've tested things more recently and it appears the updates made to this plugin since this was first submitted have thankfully made it so it doesn't get that `Error: Please complete the captcha.` error on a login attempt when using a Profile Builder login form anymore. _However_, it still doesn't show the hCaptcha challenge when enabling all available integrations (though, again, at least it doesn't flat-out break the login form anymore.)

I also tried adding the `[hcaptcha]` shortcode to the page with the Profile Builder login form (`[wppb-login]`) and, while it did output the elements for the hcaptcha sitekey, callback, nonce, etc. on the page, _unfortunately_ the hCaptcha challenge still doesn't get shown when submitting the login form (all available integrations are enabled & everything, but it just submits as if hCaptcha isn't on the site at all when using those Profile Builder forms.)

I do think it would still be great to get an official integration for the Profile Builder login, register, and forgot password forms (`[wppb-login]`, `[wppb-register]`, and `[wppb-recover-password]`, respectively) since it is a well-reviewed, actively-supported, etc. plugin with 60k+ active installs where those forms (usually presented on the front-end of a website) can be rather important to make sure they're as protected as can be.

I'd also settle for just the `[hcaptcha]` shortcode method working with these forms if making a more formal integration is too time-intensive at the moment (whatever accommodations would need to be made to get that working.) Still, I'm thinking it would certainly make people feel more confident knowing this plugin has Profile Builder listed as a formal integration option if that's possible.

**Comment by kagg-design** [comment]
Thank you for your clarifications and persistence. I have added support to the v3.0.0 of the plugin, which will be released in days.
